let pricingRate = null;
const mnt = value => `₮ ${Math.round(Number(value || 0)).toLocaleString('en-US')}`;
const cnyAmount = value => Number(String(value ?? '').replace(/[^\d.]/g, ''));
const quoteMnt = value => pricingRate ? mnt(cnyAmount(value) * pricingRate.effectiveRateMnt) : 'Rate unavailable';

const bookings = [
  { ref: 'BM7K2Q', route: 'ULN → PVG', passenger: 'BATBOLD / ENKHTAIVAN', issued: '05 Aug 2026', total: '¥ 1,280.00', status: 'Ticketed' },
  { ref: 'K8M4RP', route: 'PVG → ULN', passenger: 'DULAM / SARUUL', issued: '04 Aug 2026', total: '¥ 1,460.00', status: 'Ticketed' },
  { ref: 'QF9A2N', route: 'ULN → SHA', passenger: 'ERDENE / TUMUR', issued: '04 Aug 2026', total: '¥ 1,350.00', status: 'Pending' },
  { ref: 'L3Y7CX', route: 'PVG → ULN', passenger: 'MUNKH / NARAN', issued: '02 Aug 2026', total: '¥ 1,290.00', status: 'Ticketed' }
];
bookings.push(
  { ref: 'NEW2RT', route: 'ULN → PVG', passenger: 'BOLD / TUVSHIN', issued: '07 Aug 2026', total: '¥ 2,680.00', status: 'Ticketed', passengerCount: 1, legStates: { outbound: 'active', return: 'active' } },
  { ref: 'ONEFLW', route: 'ULN → PVG', passenger: 'SUKH / MUNKH', issued: '01 Aug 2026', total: '¥ 2,520.00', status: 'Partially flown', passengerCount: 1, legStates: { outbound: 'flown', return: 'active' } },
  { ref: 'TWOACT', route: 'ULN → PVG', passenger: 'BAYAR / SOLONGO', issued: '06 Aug 2026', total: '¥ 5,360.00', status: 'Ticketed', passengerCount: 2, passengers: ['BAYAR / SOLONGO', 'BATBOLD / TUVSHIN'], legStates: { outbound: 'active', return: 'active' } },
  { ref: 'TWOUSE', route: 'ULN → PVG', passenger: 'TUMUR / ERDENE', issued: '20 Jul 2026', total: '¥ 5,120.00', status: 'Flown', passengerCount: 2, passengers: ['TUMUR / ERDENE', 'DULAM / SARUUL'], legStates: { outbound: 'flown', return: 'flown' } }
);
bookings.splice(0, bookings.length,
  { ref: 'RTA001', route: 'ULN → PVG', passenger: 'BATBOLD / TUVSHIN', issued: '07 Aug 2026', total: '¥ 2,680.00', status: 'Ticketed', passengerCount: 1, legStates: { outbound: 'active', return: 'active' } },
  { ref: 'RTP002', route: 'ULN → PVG', passenger: 'ERDENE / DULAM', issued: '01 Aug 2026', total: '¥ 2,520.00', status: 'Partially flown', passengerCount: 1, legStates: { outbound: 'flown', return: 'active' } },
  { ref: 'RTU003', route: 'ULN → PVG', passenger: 'MUNKH / NARAN', issued: '20 Jul 2026', total: '¥ 2,560.00', status: 'Flown', passengerCount: 1, legStates: { outbound: 'flown', return: 'flown' } },
  { ref: 'OWN004', route: 'ULN → SHA', passenger: 'SARUUL / OYUN', issued: '07 Aug 2026', total: '¥ 1,340.00', status: 'Ticketed', passengerCount: 1, oneWay: true, legStates: { outbound: 'active' } },
  { ref: 'OWU005', route: 'PVG → ULN', passenger: 'TUMUR / BOLD', issued: '19 Jul 2026', total: '¥ 1,280.00', status: 'Flown', passengerCount: 1, oneWay: true, legStates: { outbound: 'flown' } },
  { ref: '2RTA06', route: 'ULN → PVG', passenger: 'BAYAR / SOLONGO', issued: '07 Aug 2026', total: '¥ 5,360.00', status: 'Ticketed', passengerCount: 2, passengers: ['BAYAR / SOLONGO', 'BATBOLD / TUVSHIN'], legStates: { outbound: 'active', return: 'active' } },
  { ref: '2RTP07', route: 'ULN → PVG', passenger: 'DULAM / ERDENE', issued: '01 Aug 2026', total: '¥ 5,040.00', status: 'Partially flown', passengerCount: 2, passengers: ['DULAM / ERDENE', 'MUNKH / NARAN'], legStates: { outbound: 'flown', return: 'active' } },
  { ref: '2RTU08', route: 'ULN → PVG', passenger: 'OYUN / SARUUL', issued: '20 Jul 2026', total: '¥ 5,120.00', status: 'Flown', passengerCount: 2, passengers: ['OYUN / SARUUL', 'TUMUR / BOLD'], legStates: { outbound: 'flown', return: 'flown' } },
  { ref: '2OWN09', route: 'ULN → SHA', passenger: 'GANBOLD / ENKHTAIVAN', issued: '07 Aug 2026', total: '¥ 2,680.00', status: 'Ticketed', passengerCount: 2, passengers: ['GANBOLD / ENKHTAIVAN', 'BAYAR / SOLONGO'], oneWay: true, legStates: { outbound: 'active' } },
  { ref: '2OWU10', route: 'PVG → ULN', passenger: 'NARAN / MUNKH', issued: '19 Jul 2026', total: '¥ 2,560.00', status: 'Flown', passengerCount: 2, passengers: ['NARAN / MUNKH', 'DULAM / ERDENE'], oneWay: true, legStates: { outbound: 'flown' } }
);
const ledger = [
  ['05 Aug 2026, 09:42', 'TKT-BM7K2Q', 'Ticket issue · ULN → PVG', 'Debit', '− ¥ 1,280.00', '¥ 12,480.00'],
  ['04 Aug 2026, 15:18', 'TKT-K8M4RP', 'Ticket issue · PVG → ULN', 'Debit', '− ¥ 1,460.00', '¥ 13,760.00'],
  ['01 Aug 2026, 11:05', 'TOP-10681', 'Top-up approved by finance', 'Credit', '+ ¥ 15,000.00', '¥ 15,220.00'],
  ['31 Jul 2026, 16:34', 'TKT-L3Y7CX', 'Ticket issue · PVG → ULN', 'Debit', '− ¥ 1,290.00', '¥ 220.00']
];
const ownBookingRefs = new Set(['RTA001', 'RTP002', 'RTU003', 'OWN004', 'OWU005', '2RTA06', '2RTP07', '2RTU08', '2OWN09', '2OWU10']);
const bookingRows = (rows, withAction = false) => rows.map(b => `<tr><td><strong>${b.ref}</strong></td><td>${b.route}</td><td>${b.passenger}</td><td>${b.issued}</td><td><strong>${b.total}</strong></td><td><span class="tag ${b.status.toLowerCase()}">${b.status}</span></td>${withAction ? `<td><button class="text-btn view-booking" data-booking-ref="${b.ref}">View</button></td>` : ''}</tr>`).join('') || `<tr><td colspan="${withAction ? 7 : 6}" class="no-bookings">No matching bookings found.</td></tr>`;
const ownBookings = () => bookings.filter(booking => ownBookingRefs.has(booking.ref));
let bookingScope = 'agent';
const renderBookings = (query = '') => {
  const normalized = query.trim().toLowerCase();
  const displayed = normalized ? bookings.filter(booking => `${booking.ref} ${booking.passenger}`.toLowerCase().includes(normalized)) : (bookingScope === 'agent' ? ownBookings() : bookings);
  document.querySelector('#recent-bookings').innerHTML = bookingRows(bookingScope === 'agent' ? ownBookings() : bookings);
  document.querySelector('#all-bookings').innerHTML = bookingRows(displayed, true);
};
window.applyBookingScope = role => {
  bookingScope = role === 'office' ? 'office' : 'agent';
  const input = document.querySelector('#bookings .filters input');
  if (input) {
    input.value = '';
    input.placeholder = bookingScope === 'agent' ? 'Search your office by PNR or passenger' : 'Search PNR, passenger or ticket number';
  }
  const description = document.querySelector('#bookings .section-heading > div > p:not(.eyebrow)');
  if (description) description.textContent = bookingScope === 'agent' ? 'Your bookings. Search your office by PNR or passenger.' : 'All bookings created by your agency.';
  renderBookings();
};
renderBookings();
document.querySelector('#bookings .filters input').addEventListener('input', event => renderBookings(event.target.value));
const bookingDetailModal = () => {
  let modal = document.querySelector('#booking-detail-modal');
  if (modal) return modal;
  modal = document.createElement('dialog');
  modal.id = 'booking-detail-modal';
  document.body.append(modal);
  return modal;
};
const bookingFlightDetails = booking => {
  const [from, to] = booking.route.split('â†’').map(value => value.trim());
  return `<div class="booking-flight-detail"><div><span>OUTBOUND</span><strong>${from || 'ULN'} â†’ ${to || 'PVG'}</strong><small>Spring Airlines Â· 9C 7058 Â· Economy</small></div><b>13:00 â†’ 17:00</b></div><div class="booking-flight-detail"><div><span>RETURN</span><strong>${to || 'PVG'} â†’ ${from || 'ULN'}</strong><small>Spring Airlines Â· 9C 7057 Â· Economy</small></div><b>08:10 â†’ 12:00</b></div>`;
};
const bookingFlightDetailsClean = booking => {
  const [from = 'ULN', to = 'PVG'] = booking.route.match(/[A-Z]{3}/g) || [];
  const states = booking.legStates || { outbound: 'active', return: 'active' };
  const flightRow = (label, route, number, times, date, state) => `<div class="booking-flight-detail ${state === 'flown' ? 'flown-flight' : ''}"><div><span>${label}</span><strong>${route}</strong><small>${date} &middot; Spring Airlines &middot; ${number} &middot; Economy</small></div><div class="flight-detail-right"><b>${times}</b><em class="segment-status ${state === 'flown' ? 'flown' : 'ticketed'}">${state === 'flown' ? 'Flown' : 'Ticketed'}</em></div></div>`;
  const outbound = flightRow(booking.oneWay ? 'ONE WAY' : 'OUTBOUND', `${from} &rarr; ${to}`, '9C 7058', '13:00 &rarr; 17:00', states.outbound === 'flown' ? 'Thu, 30 Jul 2026' : 'Thu, 20 Aug 2026', states.outbound);
  const returnFlight = booking.oneWay ? '' : flightRow('RETURN', `${to} &rarr; ${from}`, '9C 7057', '08:10 &rarr; 12:00', states.return === 'flown' ? 'Thu, 06 Aug 2026' : 'Thu, 27 Aug 2026', states.return);
  return `${outbound}${returnFlight}`;
};
const openBookingDetail = ref => {
  const booking = bookings.find(item => item.ref === ref);
  if (!booking) return;
  const modal = bookingDetailModal();
  const passengers = booking.passengers || [booking.passenger];
  const allFlightsUsed = bookingLegs(booking).every(leg => leg.flown);
  const passengerDescription = `${booking.passengerCount || passengers.length} Adult${(booking.passengerCount || passengers.length) > 1 ? 's' : ''} &middot; Passport details verified before ticketing`;
  const passengerList = passengers.map((name, index) => {
    const type = booking.passengerTypes?.[index] || 'ADT';
    const passport = ['E1234567', 'E7654321', 'A8901234'][index] || `E${1234000 + index}`;
    const birthDate = ['1988-04-12', '1991-09-23', '2016-01-08'][index] || '1990-01-01';
    const expiryDate = ['2031-04-12', '2033-09-23', '2030-01-08'][index] || '2032-01-01';
    const gender = ['Male', 'Female', 'Female'][index] || 'Male';
    return `<div class="passenger-entry"><div class="passenger-name-row"><strong>${index + 1}. ${name}</strong><b class="passenger-type">${type}</b></div><span>Passport details verified</span><div class="passenger-document"><span>Passport number</span><b>${passport}</b><span>Date of birth</span><b>${birthDate}</b><span>Gender</span><b>${gender}</b><span>Nationality</span><b>Mongolia</b><span>Passport expiry</span><b>${expiryDate}</b></div></div>`;
  }).join('');
  modal.innerHTML = `<section class="booking-detail"><button class="close booking-close" type="button" aria-label="Close">&times;</button><p class="eyebrow">BOOKING DETAILS</p><h2>${booking.ref}</h2><div class="detail-status"><span class="tag ${booking.status.toLowerCase()}">${booking.status}</span><span>Issued ${booking.issued}</span></div><section class="booking-detail-card"><h3>Itinerary</h3>${bookingFlightDetailsClean(booking)}</section><section class="booking-detail-card booking-passenger"><h3>Passengers</h3>${passengerList}<span class="passenger-summary">${passengerDescription}</span></section><section class="booking-detail-card contact-detail"><h3>Contact person</h3><strong>Bayar Agency</strong><span>+976 8011 5627 &middot; booking@bayaragency.mn</span></section><section class="booking-detail-card booking-fare"><span>Total paid</span><strong>${booking.total}</strong><small>Fare and taxes included</small></section><div class="booking-detail-actions"><button type="button" class="secondary cancel-ticket" ${allFlightsUsed ? 'disabled' : ''}>Cancel ticket</button><button type="button" class="primary change-ticket" ${allFlightsUsed ? 'disabled' : ''}>Change booking</button></div>${allFlightsUsed ? '<p class="fully-used-note">This ticket has been fully used. Cancellation and changes are unavailable.</p>' : '<p class="booking-disclaimer">Fees shown before confirmation are estimates. The final amount is confirmed by the airline.</p>'}</section>`;
  modal.querySelector('.booking-close').addEventListener('click', () => modal.close());
  modal.querySelector('.cancel-ticket').addEventListener('click', () => showCancelFlow(modal, booking));
  modal.querySelector('.change-ticket').addEventListener('click', () => showChangeFlow(modal, booking));
  modal.showModal();
};
const showCancelEstimate = (modal, booking) => {
  modal.innerHTML = `<section class="booking-detail"><button class="close booking-close" type="button" aria-label="Close">Ã—</button><p class="eyebrow">CANCEL TICKET</p><h2>Cancellation estimate</h2><p class="modal-copy">Review the estimated refund before submitting this ticket cancellation request.</p><section class="fee-summary"><div><span>Original ticket amount</span><b>${booking.total}</b></div><div><span>Airline cancellation fee</span><b>âˆ’ Â¥ 320.00</b></div><div><span>Service fee</span><b>âˆ’ Â¥ 60.00</b></div><div class="fee-total"><span>Estimated refund</span><strong>Â¥ 900.00</strong></div></section><p class="booking-warning">After confirmation, the cancellation is sent to the airline. Final refund is subject to fare rules and airline approval.</p><div class="booking-detail-actions"><button type="button" class="secondary back-booking">Back</button><button type="button" class="primary confirm-cancel">Confirm cancellation</button></div></section>`;
  modal.querySelector('.booking-close').addEventListener('click', () => modal.close());
  modal.querySelector('.back-booking').addEventListener('click', () => openBookingDetail(booking.ref));
  modal.querySelector('.confirm-cancel').addEventListener('click', () => { modal.close(); toast(`Cancellation request for ${booking.ref} created. Estimated refund: Â¥ 900.00.`); });
};
const showChangeEstimate = (modal, booking) => {
  modal.innerHTML = `<section class="booking-detail"><button class="close booking-close" type="button" aria-label="Close">Ã—</button><p class="eyebrow">CHANGE BOOKING</p><h2>Change itinerary</h2><p class="modal-copy">Choose which flight to change, then select the requested new travel date.</p><section class="change-options"><label><input type="radio" name="change-scope" value="both" checked /> Change both flights</label><label><input type="radio" name="change-scope" value="outbound" /> Departure flight only</label><label><input type="radio" name="change-scope" value="return" /> Return flight only</label></section><label class="change-date">New travel date<input type="date" min="2026-08-08" value="2026-08-25" /></label><section class="fee-summary change-estimate" hidden><div><span>Airline change fee</span><b>Â¥ 150.00</b></div><div><span>Estimated fare difference</span><b>Â¥ 180.00</b></div><div class="fee-total"><span>Estimated additional payment</span><strong>Â¥ 330.00</strong></div></section><div class="booking-detail-actions"><button type="button" class="secondary back-booking">Back</button><button type="button" class="primary calculate-change">Calculate change</button><button type="button" class="primary confirm-change" hidden>Confirm change request</button></div></section>`;
  modal.querySelector('.booking-close').addEventListener('click', () => modal.close());
  modal.querySelector('.back-booking').addEventListener('click', () => openBookingDetail(booking.ref));
  modal.querySelector('.calculate-change').addEventListener('click', event => { modal.querySelector('.change-estimate').hidden = false; modal.querySelector('.confirm-change').hidden = false; event.currentTarget.textContent = 'Recalculate'; });
  modal.querySelector('.confirm-change').addEventListener('click', () => { modal.close(); toast(`Change request for ${booking.ref} created. Estimated additional payment: Â¥ 330.00.`); });
};
const bookingLegs = booking => {
  const [from = 'ULN', to = 'PVG'] = booking.route.match(/[A-Z]{3}/g) || [];
  const states = booking.legStates || { outbound: booking.ref === 'L3Y7CX' ? 'flown' : 'active', return: 'active' };
  const legs = [{ key: 'outbound', route: `${from} &rarr; ${to}`, flight: 'Spring Airlines &middot; 9C 7058', time: '13:00 &rarr; 17:00', flown: states.outbound === 'flown' }];
  if (!booking.oneWay) legs.push({ key: 'return', route: `${to} &rarr; ${from}`, flight: 'Spring Airlines &middot; 9C 7057', time: '08:10 &rarr; 12:00', flown: states.return === 'flown' });
  return legs;
};
const flightChoice = (leg, mode, checked = false) => `<label class="flight-choice ${leg.flown ? 'flown' : ''}"><input type="checkbox" name="${mode}-leg" value="${leg.key}" ${checked && !leg.flown ? 'checked' : ''} ${leg.flown ? 'disabled' : ''}/><span class="flight-choice-copy"><small>${leg.flown ? 'FLOWN' : 'ACTIVE FLIGHT'}</small><strong>${leg.route}</strong><em>${leg.flight}</em></span><b>${leg.time}</b><i>${leg.flown ? 'Used' : 'Select'}</i></label>`;
const passengerChoices = (booking, mode) => (booking.passengers || [booking.passenger]).map((passenger, index) => `<label class="passenger-choice"><input type="checkbox" name="${mode}-passenger" value="${index}" checked /><span><strong>${index + 1}. ${passenger}</strong><small>Adult passenger</small></span></label>`).join('');
const yen = value => `¥ ${Number(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const showCancelSelection = (modal, booking) => {
  const legs = bookingLegs(booking);
  modal.innerHTML = `<section class="booking-detail"><button class="close booking-close" type="button" aria-label="Close">&times;</button><p class="eyebrow">CANCEL TICKET</p><h2>Select flights and passengers</h2><p class="modal-copy">Choose the flight and passenger(s) to cancel. A flown segment cannot be cancelled.</p><section class="selection-group"><h3>Flights</h3><section class="flight-choice-list">${legs.map(leg => flightChoice(leg, 'cancel', !leg.flown)).join('')}</section></section><section class="selection-group"><h3>Passengers</h3><section class="passenger-choice-list">${passengerChoices(booking, 'cancel')}</section></section><section class="fee-summary cancel-estimate" hidden></section><p class="booking-warning" hidden>After confirmation, the cancellation is sent to the airline. The final refund is subject to airline fare rules and approval.</p><div class="booking-detail-actions"><button type="button" class="secondary back-booking">Back</button><button type="button" class="primary calculate-cancel">Calculate refund</button><button type="button" class="primary confirm-cancel" hidden>Confirm cancellation</button></div></section>`;
  modal.querySelector('.booking-close').addEventListener('click', () => modal.close());
  modal.querySelector('.back-booking').addEventListener('click', () => openBookingDetail(booking.ref));
  modal.querySelector('.calculate-cancel').addEventListener('click', event => {
    const selected = [...modal.querySelectorAll('[name="cancel-leg"]:checked')];
    const selectedPassengers = modal.querySelectorAll('[name="cancel-passenger"]:checked').length;
    if (!selected.length || !selectedPassengers) { modal.querySelector('.cancel-estimate').hidden = true; modal.querySelector('.booking-warning').hidden = true; modal.querySelector('.confirm-cancel').hidden = true; return; }
    const ticketAmount = Number(String(booking.total).replace(/[^\d.]/g, '')) * (selected.length / legs.length) * (selectedPassengers / (booking.passengerCount || 1));
    const airlineFee = ticketAmount * .25;
    const serviceFee = 30 * selected.length * selectedPassengers;
    const estimate = { amount: yen(ticketAmount), airline: `− ${yen(airlineFee)}`, service: `− ${yen(serviceFee)}`, refund: yen(Math.max(0, ticketAmount - airlineFee - serviceFee)) };
    modal.querySelector('.cancel-estimate').innerHTML = `<div><span>Selected ticket amount</span><b>${estimate.amount}</b></div><div><span>Airline cancellation fee</span><b>${estimate.airline}</b></div><div><span>Service fee</span><b>${estimate.service}</b></div><div class="fee-total"><span>Refund</span><strong>${estimate.refund}</strong></div>`;
    modal.querySelector('.cancel-estimate').hidden = false;
    modal.querySelector('.booking-warning').hidden = false;
    modal.querySelector('.confirm-cancel').hidden = false;
    event.currentTarget.textContent = 'Recalculate refund';
  });
  const cancelCalculator = modal.querySelector('.calculate-cancel');
  modal.querySelectorAll('[name="cancel-leg"], [name="cancel-passenger"]').forEach(input => input.addEventListener('change', () => cancelCalculator.click()));
  cancelCalculator.click();
  modal.querySelector('.confirm-cancel').addEventListener('click', () => { modal.close(); toast(`Cancellation request for ${booking.ref} created.`); });
};
const showChangeSelection = (modal, booking) => {
  const legs = bookingLegs(booking);
  const renderDates = () => [...modal.querySelectorAll('[name="change-leg"]:checked')].map(input => `<label class="change-date"><span>New date for ${input.value === 'outbound' ? 'departure flight' : 'return flight'}</span><input type="date" min="2026-08-08" value="2026-08-25" /></label>`).join('') || '<p class="selection-hint">Select an active flight to choose a new date.</p>';
  modal.innerHTML = `<section class="booking-detail"><button class="close booking-close" type="button" aria-label="Close">&times;</button><p class="eyebrow">CHANGE BOOKING</p><h2>Select flights and passengers</h2><p class="modal-copy">Choose the flight and passenger(s) to change. Used segments are shown as Flown and cannot be changed.</p><section class="selection-group"><h3>Flights</h3><section class="flight-choice-list">${legs.map(leg => flightChoice(leg, 'change', !leg.flown)).join('')}</section></section><section class="selection-group"><h3>Passengers</h3><section class="passenger-choice-list">${passengerChoices(booking, 'change')}</section></section><section class="change-date-list"></section><section class="fee-summary change-estimate" hidden></section><div class="booking-detail-actions"><button type="button" class="secondary back-booking">Back</button><button type="button" class="primary calculate-change">Calculate change</button><button type="button" class="primary confirm-change" hidden>Confirm change request</button></div></section>`;
  const dateList = modal.querySelector('.change-date-list');
  const refreshDates = () => { dateList.innerHTML = renderDates(); };
  refreshDates();
  modal.querySelectorAll('[name="change-leg"]').forEach(input => input.addEventListener('change', refreshDates));
  modal.querySelector('.booking-close').addEventListener('click', () => modal.close());
  modal.querySelector('.back-booking').addEventListener('click', () => openBookingDetail(booking.ref));
  modal.querySelector('.calculate-change').addEventListener('click', event => {
    const selected = modal.querySelectorAll('[name="change-leg"]:checked').length;
    const selectedPassengers = modal.querySelectorAll('[name="change-passenger"]:checked').length;
    if (!selected || !selectedPassengers) { modal.querySelector('.change-estimate').hidden = true; modal.querySelector('.confirm-change').hidden = true; return; }
    const changeFee = 150 * selected * selectedPassengers;
    const fareDifference = 180 * selected * selectedPassengers;
    const total = changeFee + fareDifference;
    modal.querySelector('.change-estimate').innerHTML = `<div><span>Airline change fee</span><b>${yen(changeFee)}</b></div><div><span>Fare difference</span><b>${yen(fareDifference)}</b></div><div class="fee-total"><span>Additional payment</span><strong>${yen(total)}</strong></div>`;
    modal.querySelector('.change-estimate').hidden = false;
    modal.querySelector('.confirm-change').hidden = false;
    event.currentTarget.textContent = 'Recalculate change';
  });
  const changeCalculator = modal.querySelector('.calculate-change');
  modal.querySelectorAll('[name="change-leg"], [name="change-passenger"]').forEach(input => input.addEventListener('change', () => changeCalculator.click()));
  changeCalculator.click();
  modal.querySelector('.confirm-change').addEventListener('click', () => { modal.close(); toast(`Change request for ${booking.ref} created.`); });
};
const selectedPassengerNames = (modal, mode, booking) => [...modal.querySelectorAll(`[name="${mode}-passenger"]:checked`)].map(input => (booking.passengers || [booking.passenger])[Number(input.value)]);
const showCancelFlow = (modal, booking) => {
  const legs = bookingLegs(booking);
  modal.innerHTML = `<section class="booking-detail"><button class="close booking-close" type="button">&times;</button><p class="eyebrow">CANCEL TICKET</p><h2>Select flights and passengers</h2><p class="modal-copy">Choose the flight and passenger(s) to cancel. Flown flights cannot be cancelled.</p><section class="selection-group"><h3>Itinerary</h3><section class="flight-choice-list">${legs.map(leg => flightChoice(leg, 'cancel-flow', !leg.flown)).join('')}</section></section><section class="selection-group"><h3>Passengers</h3><section class="passenger-choice-list">${passengerChoices(booking, 'cancel-flow')}</section></section><div class="booking-detail-actions"><button type="button" class="secondary back-booking">Back</button><button type="button" class="primary calculate-cancel-flow">Calculate refund</button></div></section>`;
  modal.querySelector('.booking-close').addEventListener('click', () => modal.close());
  modal.querySelector('.back-booking').addEventListener('click', () => openBookingDetail(booking.ref));
  modal.querySelector('.calculate-cancel-flow').addEventListener('click', () => {
    const selectedLegs = legs.filter(leg => modal.querySelector(`[name="cancel-flow-leg"][value="${leg.key}"]`)?.checked);
    const passengers = selectedPassengerNames(modal, 'cancel-flow', booking);
    if (!selectedLegs.length || !passengers.length) return toast('Select at least one active flight and one passenger.');
    const ticketAmount = Number(String(booking.total).replace(/[^\d.]/g, '')) * (selectedLegs.length / legs.length) * (passengers.length / (booking.passengerCount || 1));
    const airlineFee = ticketAmount * .25; const serviceFee = 30 * selectedLegs.length * passengers.length; const refund = Math.max(0, ticketAmount - airlineFee - serviceFee);
    modal.innerHTML = `<section class="booking-detail"><button class="close booking-close" type="button">&times;</button><p class="eyebrow">CANCEL TICKET</p><h2>Cancellation summary</h2><section class="summary-selection"><h3>Flights to cancel</h3>${selectedLegs.map(leg => `<div><strong>${leg.route}</strong><span>${leg.flight} &middot; ${leg.time}</span></div>`).join('')}<h3>Passengers</h3><p>${passengers.join(' &middot; ')}</p></section><section class="fee-summary"><div><span>Selected ticket amount</span><b>${yen(ticketAmount)}</b></div><div><span>Airline cancellation fee</span><b>− ${yen(airlineFee)}</b></div><div><span>Service fee</span><b>− ${yen(serviceFee)}</b></div><div class="fee-total"><span>Refund</span><strong>${yen(refund)}</strong></div></section><p class="booking-warning">The final refund is subject to airline fare rules and approval.</p><div class="booking-detail-actions"><button type="button" class="secondary back-booking">Back</button><button type="button" class="primary confirm-cancel">Confirm cancellation</button></div></section>`;
    modal.querySelector('.booking-close').addEventListener('click', () => modal.close());
    modal.querySelector('.back-booking').addEventListener('click', () => showCancelFlow(modal, booking));
    modal.querySelector('.confirm-cancel').addEventListener('click', () => { modal.close(); toast(`Cancellation request for ${booking.ref} created.`); });
  });
};
const showChangeFlow = (modal, booking) => {
  const legs = bookingLegs(booking);
  const replacements = leg => {
    const flightNumber = leg.key === 'outbound' ? '9C 7058' : '9C 7057';
    const flightTime = leg.key === 'outbound' ? '13:00 → 17:00' : '08:10 → 12:00';
    const days = '';
    return `<section class="replacement-flight" data-for="${leg.key}"><div class="replacement-title"><span>New date for ${leg.key === 'outbound' ? 'departure flight' : 'return flight'}</span><strong>Spring Airlines &middot; ${flightNumber}</strong><small>${leg.route} &middot; ${flightTime}</small></div><button type="button" class="availability-date" data-for="${leg.key}" data-flight="${flightNumber}" data-time="${flightTime}" data-fare="">Choose a new date</button><div class="availability-calendar" hidden><div class="availability-head"><button type="button" class="availability-prev" aria-label="Previous month">‹</button><strong>August 2026</strong><button type="button" class="availability-next" aria-label="Next month">›</button></div><div class="availability-week"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div class="availability-days">${days}</div><p>Same airline and flight availability. – means no flight available.</p></div><div class="daily-flight-options"></div></section>`;
  };
  const bindAvailabilityCalendars = () => modal.querySelectorAll('.replacement-flight').forEach(section => {
    const trigger = section.querySelector('.availability-date'); const calendar = section.querySelector('.availability-calendar'); const choices = section.querySelector('.daily-flight-options'); const calendarToday = new Date(); calendarToday.setHours(0, 0, 0, 0); const calendarYear = calendarToday.getFullYear(); let shownMonth = calendarToday.getMonth();
    const renderDailyFlights = (date, baseFare) => {
      const twoFlights = Number(date.slice(-2)) % 2 === 0;
      const flight = trigger.dataset.flight; const time = trigger.dataset.time;
      const option = (number, timing, fare, checked) => `<label class="daily-flight-choice"><input type="radio" name="daily-${trigger.dataset.for}" value="${number}|${timing}|${fare}" ${checked ? 'checked' : ''}/><span><strong>Spring Airlines &middot; ${number}</strong><small>${timing} &middot; Economy</small></span><b>+ ${yen(fare)}</b></label>`;
      choices.innerHTML = `<h3>Available flights on ${date}</h3>${option(flight, time, baseFare, true)}${twoFlights ? option(flight === '9C 7058' ? '9C 7012' : '9C 7011', flight === '9C 7058' ? '16:10 → 20:15' : '14:15 → 18:05', Number(baseFare) + 80, false) : ''}<div class="pre-calculate-fare">Fare difference <strong>+ ${yen(baseFare)}</strong></div>`;
      choices.querySelectorAll('input').forEach(input => input.addEventListener('change', () => { const fare = input.value.split('|')[2]; trigger.dataset.fare = fare; trigger.dataset.flight = input.value.split('|')[0]; trigger.dataset.time = input.value.split('|')[1]; choices.querySelector('.pre-calculate-fare').innerHTML = `Fare difference <strong>+ ${yen(fare)}</strong>`; }));
    };
    const selectDay = day => { section.querySelectorAll('.availability-day').forEach(item => item.classList.remove('selected')); day.classList.add('selected'); trigger.dataset.fare = day.dataset.fare; trigger.textContent = `${day.dataset.date} · ${yen(day.dataset.fare)}`; calendar.hidden = true; renderDailyFlights(day.dataset.date, day.dataset.fare); };
    const renderMonth = () => {
      const year = calendarYear; const first = new Date(year, shownMonth, 1); const start = (first.getDay() + 6) % 7; const totalDays = new Date(year, shownMonth + 1, 0).getDate();
      calendar.querySelector('.availability-head strong').textContent = first.toLocaleString('en-US', { month: 'long', year: 'numeric' });
      const blanks = Array.from({ length: start }, () => '<span class="availability-blank"></span>').join('');
      const buttons = Array.from({ length: totalDays }, (_, index) => { const day = index + 1; const dateObject = new Date(year, shownMonth, day); const price = (day + shownMonth) % 5 === 0 ? null : 140 + ((day * 17 + shownMonth * 11) % 7) * 20; const date = `${year}-${String(shownMonth + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`; const disabled = price === null || dateObject < calendarToday; return `<button type="button" class="availability-day ${price === null ? 'unavailable' : ''}${dateObject.getTime() === calendarToday.getTime() ? ' today' : ''}" data-date="${date}" data-fare="${price ?? ''}" ${disabled ? 'disabled' : ''}><strong>${day}</strong><span>${price === null ? '–' : yen(price)}</span></button>`; }).join('');
      calendar.querySelector('.availability-days').innerHTML = `${blanks}${buttons}`;
      calendar.querySelectorAll('.availability-day:not(:disabled)').forEach(day => day.addEventListener('click', () => selectDay(day)));
    };
    trigger.addEventListener('click', () => { calendar.hidden = !calendar.hidden; });
    calendar.querySelector('.availability-prev').addEventListener('click', () => { shownMonth = Math.max(calendarToday.getMonth(), shownMonth - 1); renderMonth(); });
    calendar.querySelector('.availability-next').addEventListener('click', () => { shownMonth = Math.min(11, shownMonth + 1); renderMonth(); });
    renderMonth();
  });
  const renderReplacements = () => { const selected = legs.filter(leg => modal.querySelector(`[name="change-flow-leg"][value="${leg.key}"]`)?.checked); modal.querySelector('.replacement-list').innerHTML = selected.map(replacements).join('') || '<p class="selection-hint">Select an active flight first.</p>'; bindAvailabilityCalendars(); };
  modal.innerHTML = `<section class="booking-detail"><button class="close booking-close" type="button">&times;</button><p class="eyebrow">CHANGE BOOKING</p><h2>Select flights and passengers</h2><p class="modal-copy">Choose the itinerary and passenger(s), then select a new date and flight.</p><section class="selection-group"><h3>Itinerary</h3><section class="flight-choice-list">${legs.map(leg => flightChoice(leg, 'change-flow', !leg.flown)).join('')}</section></section><section class="selection-group"><h3>Passengers</h3><section class="passenger-choice-list">${passengerChoices(booking, 'change-flow')}</section></section><section class="replacement-list"></section><div class="booking-detail-actions"><button type="button" class="secondary back-booking">Back</button><button type="button" class="primary calculate-change-flow">Calculate change</button></div></section>`;
  renderReplacements();
  modal.querySelectorAll('[name="change-flow-leg"]').forEach(input => input.addEventListener('change', renderReplacements));
  modal.querySelector('.booking-close').addEventListener('click', () => modal.close());
  modal.querySelector('.back-booking').addEventListener('click', () => openBookingDetail(booking.ref));
  modal.querySelector('.calculate-change-flow').addEventListener('click', () => {
    const selectedLegs = legs.filter(leg => modal.querySelector(`[name="change-flow-leg"][value="${leg.key}"]`)?.checked);
    const passengers = selectedPassengerNames(modal, 'change-flow', booking);
    const selectedNewFlights = selectedLegs.map(leg => modal.querySelector(`[name="daily-${leg.key}"]:checked`));
    if (!selectedLegs.length || !passengers.length || selectedNewFlights.some(flight => !flight)) return toast('Select flights, passengers, and replacement flights.');
    const changeFee = 150 * selectedLegs.length * passengers.length;
    const fareDifference = selectedNewFlights.reduce((total, input) => total + Number(input.value.split('|')[2]) * passengers.length, 0);
    const additional = changeFee + fareDifference;
    const comparisons = selectedLegs.map((leg, index) => { const [number, time, fare] = selectedNewFlights[index].value.split('|'); return `<div class="flight-comparison"><div><small>OLD FLIGHT</small><strong>${leg.route}</strong><span>${leg.flight} &middot; ${leg.time}</span></div><i>→</i><div><small>NEW FLIGHT</small><strong>${leg.route}</strong><span>Spring Airlines &middot; ${number} &middot; ${time}</span><em>+ ${yen(fare)}</em></div></div>`; }).join('');
    modal.innerHTML = `<section class="booking-detail"><button class="close booking-close" type="button">&times;</button><p class="eyebrow">CHANGE BOOKING</p><h2>Change summary</h2><section class="summary-selection"><h3>Selected passengers</h3><p>${passengers.join(' &middot; ')}</p></section><section class="comparison-list">${comparisons}</section><section class="fee-summary"><div><span>Airline change fee</span><b>${yen(changeFee)}</b></div><div><span>Fare difference</span><b>${yen(fareDifference)}</b></div><div class="fee-total"><span>Additional payment</span><strong>${yen(additional)}</strong></div></section><div class="booking-detail-actions"><button type="button" class="secondary back-booking">Back</button><button type="button" class="primary confirm-change">Confirm change request</button></div></section>`;
    modal.querySelector('.booking-close').addEventListener('click', () => modal.close());
    modal.querySelector('.back-booking').addEventListener('click', () => showChangeFlow(modal, booking));
    modal.querySelector('.confirm-change').addEventListener('click', () => { modal.close(); toast(`Change request for ${booking.ref} created.`); });
  });
};
document.addEventListener('click', event => { const button = event.target.closest('.view-booking'); if (button) openBookingDetail(button.dataset.bookingRef); });
document.querySelector('#ledger').innerHTML = ledger.map(row => `<tr>${row.map((x,i)=> `<td class="${i===3 ? (x === 'Credit' ? 'credit' : 'debit') : ''}">${x}</td>`).join('')}</tr>`).join('');
const showView = id => { document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id)); document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id)); document.querySelector('main > header').hidden = id === 'bookings'; document.querySelector('#page-title').textContent = id==='dashboard' ? 'Good morning, Bayar' : id==='search' ? 'Flight search' : id[0].toUpperCase()+id.slice(1); window.scrollTo({top:0,behavior:'smooth'}); };
document.querySelectorAll('[data-view], [data-view-target]').forEach(btn => btn.addEventListener('click', () => showView(btn.dataset.view || btn.dataset.viewTarget)));
const formatMinutes = minutes => `${Math.floor(minutes / 60)}h ${minutes % 60}m`;
const resultArea = document.querySelector('#flight-results');
let tripType = 'round'; let visibleFlights = []; let searchPhase = 'outbound'; let selectedOutbound = null; let selectedReturn = null;
const priceText = price => price ? quoteMnt(price) : 'Price unavailable';
const timeText = flight => `${(flight.departure.time || '').slice(-5)} ${flight.departure.id || ''} → ${(flight.arrival.time || '').slice(-5)} ${flight.arrival.id || ''}`;
const flightCard = (flight, label) => `<article class="selection-card"><div class="selection-label">${label}</div><div class="selection-main"><div><strong>${flight.airline}</strong><span>${flight.number || 'Flight'} · ${timeText(flight)}</span></div><div class="selection-duration">${formatMinutes(flight.duration || 0)} · ${flight.stops ? `${flight.stops} stop${flight.stops > 1 ? 's' : ''}` : 'Nonstop'}</div><b>${priceText(flight.price)}</b></div></article>`;
const selectedOutboundPanel = () => selectedOutbound ? `<section class="selected-itinerary"><div class="selected-title"><span>✓</span><div><h2>Outbound flight selected</h2><p>Select your return flight below.</p></div></div>${flightCard(selectedOutbound, 'OUTBOUND')}</section>` : '';
const totalPrice = () => { const numbers = [selectedOutbound, selectedReturn].map(f => cnyAmount(f?.price)).filter(Number.isFinite); return numbers.length ? quoteMnt(numbers.reduce((sum, value) => sum + value, 0)) : 'Price unavailable'; };
const airportNames = { UBN: 'Chinggis Khaan International Airport', ULN: 'Chinggis Khaan International Airport', PVG: 'Shanghai Pudong International Airport', SHA: 'Shanghai Hongqiao International Airport', PEK: 'Beijing Capital International Airport', PKX: 'Beijing Daxing International Airport', HKG: 'Hong Kong International Airport', NRT: 'Tokyo Narita International Airport', ICN: 'Seoul Incheon International Airport' };
const mockFlight = (departure, arrival, number, departureTime, arrivalTime, price, airline = 'Spring') => ({ airline, number, duration: 250, stops: 0, price: String(price), departure: { id: departure, time: departureTime, name: airportNames[departure] || `${departure} Airport` }, arrival: { id: arrival, time: arrivalTime, name: airportNames[arrival] || `${arrival} Airport` }, segments: [{ airline, number, duration: 250, departure: { id: departure, time: departureTime, name: airportNames[departure] || `${departure} Airport` }, arrival: { id: arrival, time: arrivalTime, name: airportNames[arrival] || `${arrival} Airport` }, airplane: 'Airbus A320', travelClass: 'Economy' }] });
const mockSearchResults = (departure, arrival) => [mockFlight(departure, arrival, '9C 7058', '13:00', '17:00', 2095), mockFlight(departure, arrival, '9C 7012', '08:10', '12:05', 2360), mockFlight(departure, arrival, '9C 7026', '18:30', '22:30', 2580)];
const showMockSearch = (departure, arrival) => { const outbound = mockSearchResults(departure, arrival); if (tripType === 'round') { const returns = [mockFlight(arrival, departure, '9C 7057', '08:10', '12:00', 1960), mockFlight(arrival, departure, '9C 7011', '14:15', '18:05', 2150), mockFlight(arrival, departure, '9C 7025', '19:20', '23:15', 2290)]; renderRoundPairs(outbound.map((flight, index) => ({ outbound: flight, returnFlight: returns[index], sameAirline: true }))); } else renderFlights(outbound, 'outbound'); };
const showItinerary = () => { resultArea.classList.remove('hidden'); resultArea.innerHTML = `<section class="final-itinerary"><div class="selected-title"><span>✓</span><div><p class="eyebrow">ROUND TRIP SELECTED</p><h2>Your selected itinerary</h2></div></div>${flightCard(selectedOutbound, 'OUTBOUND')} ${flightCard(selectedReturn, 'RETURN')}<div class="fare-total"><span>Total fare for selected flights</span><strong>${totalPrice()}</strong></div><button class="primary continue-ticket">Continue to passenger details</button></section>`; document.querySelector('.continue-ticket').addEventListener('click', () => document.querySelector('#ticket-modal').showModal()); };
const checkoutFlight = (flight, label) => flight ? `<article class="checkout-flight"><div><span class="journey-tag ${label.toLowerCase()}">${label}</span><b>${flight.airline || 'Airline'} ${flight.number || ''}</b></div><div class="checkout-times"><strong>${(flight.departure?.time || '').slice(-5)}</strong><i></i><strong>${(flight.arrival?.time || '').slice(-5)}</strong></div><div class="checkout-airports"><span>${flight.departure?.name || flight.departure?.id || ''} (${flight.departure?.id || ''})</span><span>${flight.arrival?.name || flight.arrival?.id || ''} (${flight.arrival?.id || ''})</span></div></article>` : '';
const passengerForm = (type, index) => `<section class="passenger-card"><div class="passenger-card-title"><h2>${index + 1} ${type}</h2></div><div class="passenger-fields"><label>Last name<input required placeholder="As shown on document" /></label><label>First name<input required placeholder="First and middle names" /></label><label>Date of birth<input type="date" required /></label><label>Document type<select><option>Passport</option><option>National ID</option></select></label><label>Document number<input required /></label><label>Issuing country / region<input required placeholder="e.g. Mongolia" /></label><label>Document expiry<input type="date" required /></label><label>Nationality / region<input required placeholder="e.g. Mongolia" /></label><label>Gender<select required><option value="">Select</option><option>Male</option><option>Female</option></select></label></div></section>`;
const showCheckout = () => { const counts = [['Adult', Number(document.querySelector('#adults').value)], ['Child', Number(document.querySelector('#children').value)], ['Infant', Number(document.querySelector('#infants').value)]]; const passengers = counts.flatMap(([type, count]) => Array.from({ length: count }, (_, index) => passengerForm(type, index))); resultArea.classList.remove('hidden'); resultArea.innerHTML = `<section class="passenger-checkout"><div class="checkout-main"><div class="checkout-heading"><p class="eyebrow">PASSENGER DETAILS</p><h2>Enter passenger information</h2><p>Names must match the travel document exactly.</p></div><form id="passenger-form">${passengers.join('')}<section class="contact-card"><h2>Contact person</h2><div class="passenger-fields"><label>Full name<input required /></label><label>Contact number<input type="tel" required /></label><label>Email address<input type="email" required /></label></div><p>Booking confirmation and schedule changes will be sent to this contact.</p></section><button class="primary issue-ticket" type="submit">Continue to payment</button></form></div><aside class="order-summary"><h2>Order details</h2>${checkoutFlight(selectedOutbound, 'Departure')}${checkoutFlight(selectedReturn, 'Arrival')}<div class="summary-total"><span>Total fare</span><strong>${totalPrice()}</strong><small>Final fare and tax are confirmed before ticket issuance.</small></div></aside></section>`; document.querySelector('#passenger-form').addEventListener('submit', event => { event.preventDefault(); document.querySelector('#ticket-modal').showModal(); }); resultArea.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair')) showCheckout(); });
const airportCode = value => value.match(/\(([A-Z]{3})\)/i)?.[1] || value.trim().toUpperCase();
const showToast = message => toast(message);
const collapseCountryFields = () => { document.querySelectorAll('.passenger-card').forEach(card => { const labels = [...card.querySelectorAll('label')]; const issuing = labels.find(label => label.textContent.includes('Issuing country')); const nationality = labels.find(label => label.textContent.includes('Nationality')); const visible = nationality?.querySelector('input:not([type="hidden"])'); if (!issuing || !nationality || !visible) return; let hidden = nationality.querySelector('input[type="hidden"][name="issuing-country"]'); if (!hidden) { hidden = document.createElement('input'); hidden.type = 'hidden'; hidden.name = 'issuing-country'; nationality.append(hidden); visible.addEventListener('input', () => { hidden.value = visible.value; }); visible.addEventListener('change', () => { hidden.value = visible.value; }); } const textNode = [...nationality.childNodes].find(node => node.nodeType === Node.TEXT_NODE); if (textNode) textNode.textContent = 'Nationality (country/region)'; hidden.value = visible.value; issuing.remove(); }); };
new MutationObserver(collapseCountryFields).observe(resultArea, { childList: true, subtree: true });
const combineCountryNationality = () => { document.querySelectorAll('.passenger-card').forEach(card => { const labels = [...card.querySelectorAll('label')]; const issuing = labels.find(label => label.textContent.includes('Issuing country')); const nationality = labels.find(label => label.textContent.includes('Nationality')); if (!issuing || !nationality) return; issuing.hidden = true; const textNode = [...nationality.childNodes].find(node => node.nodeType === Node.TEXT_NODE); if (textNode) textNode.textContent = 'Nationality (country/region)'; }); };
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair') || (event.target.closest('.book-flight') && tripType !== 'round')) setTimeout(combineCountryNationality, 0); });
const allCountryNames = () => { const codes = 'AF AX AL DZ AS AD AO AI AQ AG AR AM AW AU AT AZ BS BH BD BB BY BE BZ BJ BM BT BO BQ BA BW BV BR IO BN BG BF BI CV KH CM CA KY CF TD CL CN CX CC CO KM CG CD CK CR CI HR CU CW CY CZ DK DJ DM DO EC EG SV GQ ER EE SZ ET FK FO FJ FI FR GF PF TF GA GM GE DE GH GI GR GL GD GP GU GT GG GN GW GY HT HM VA HN HK HU IS IN ID IR IQ IE IM IL IT JM JP JE JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MO MG MW MY MV ML MT MQ MR MU YT MX FM MD MC MN ME MS MA MZ MM NA NR NP NL NC NZ NI NE NG NG NU NF MK MP NO OM PK PW PS PA PG PY PE PH PN PL PT PR QA RE RO RU RW BL SH KN LC MF PM VC WS SM ST SA SN RS SC SL SG SX SK SI SB SO ZA GS SS ES LK SD SR SJ SE CH SY TW TJ TZ TH TL TG TK TO TT TN TR TM TC TV UG UA AE GB US UM UY UZ VU VE VN VG VI WF EH YE ZM ZW XK'.split(' '); const names = new Intl.DisplayNames(['en'], { type: 'region' }); return [...new Set(codes.map(code => names.of(code)).filter(name => name && name.length > 2))].sort((a, b) => a.localeCompare(b)); };
const enhanceCountryMenus = () => { const countries = allCountryNames(); const render = (menu, query) => { const matches = countries.filter(country => country.toLowerCase().includes(query.toLowerCase())); let letter = ''; menu.innerHTML = matches.map(country => { const first = country[0].toUpperCase(); const heading = first === letter ? '' : `<div class="country-letter">${first}</div>`; letter = first; return `${heading}<button type="button" data-country="${country}">${country}</button>`; }).join('') || '<div class="country-letter">No matching country</div>'; }; document.querySelectorAll('.passenger-card').forEach(card => { const labels = [...card.querySelectorAll('label')]; ['Issuing country', 'Nationality'].forEach(text => { const label = labels.find(item => item.textContent.includes(text)); const input = label?.querySelector('input'); if (!label || !input || input.dataset.countryMenuBound) return; input.removeAttribute('list'); input.dataset.countryMenuBound = 'true'; const menu = document.createElement('div'); menu.className = 'country-menu'; menu.hidden = true; label.append(menu); const open = () => { render(menu, input.value); menu.hidden = false; }; input.addEventListener('focus', open); input.addEventListener('input', open); menu.addEventListener('click', event => { const option = event.target.closest('[data-country]'); if (!option) return; input.value = option.dataset.country; input.dispatchEvent(new Event('change')); menu.hidden = true; }); document.addEventListener('click', event => { if (!label.contains(event.target)) menu.hidden = true; }); }); }); };
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair') || (event.target.closest('.book-flight') && tripType !== 'round')) queueMicrotask(bindCountryFields); });
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair') || (event.target.closest('.book-flight') && tripType !== 'round')) setTimeout(enhanceCountryMenus, 0); });
const countryNames = ['Mongolia','Russia','China','Japan','South Korea','North Korea','Kazakhstan','United States','United Kingdom','Germany','France','Turkey','Thailand','Singapore','Vietnam','India','Australia','Canada'];
const bindCountryFields = () => { let list = document.querySelector('#country-options'); if (!list) { list = document.createElement('datalist'); list.id = 'country-options'; list.innerHTML = countryNames.map(country => `<option value="${country}"></option>`).join(''); document.body.append(list); } const correctCountry = value => { const query = value.trim().toLowerCase(); return countryNames.find(country => country.toLowerCase().startsWith(query) || query.startsWith(country.toLowerCase())) || value.trim(); }; document.querySelectorAll('.passenger-card').forEach(card => { const labels = [...card.querySelectorAll('label')]; const issuing = labels.find(label => label.textContent.includes('Issuing country'))?.querySelector('input'); const nationality = labels.find(label => label.textContent.includes('Nationality'))?.querySelector('input'); if (!issuing || !nationality || issuing.dataset.countryBound) return; [issuing, nationality].forEach(input => { input.setAttribute('list', 'country-options'); input.setAttribute('autocomplete', 'off'); input.dataset.countryBound = 'true'; }); const mirror = (source, target) => { const country = correctCountry(source.value); if (country) { source.value = country; target.value = country; } }; issuing.addEventListener('change', () => mirror(issuing, nationality)); issuing.addEventListener('blur', () => mirror(issuing, nationality)); nationality.addEventListener('change', () => mirror(nationality, issuing)); nationality.addEventListener('blur', () => mirror(nationality, issuing)); }); };
const prepareBookingScreen = () => { showCheckout(); queueMicrotask(() => { openBookingScreen(); const route = document.querySelector('.booking-route'); const headerContent = document.querySelector('main > header > div'); const title = document.querySelector('#page-title'); if (!route) return; if (!route.querySelector('.back-to-search')) route.insertAdjacentHTML('beforeend', '<button type="button" class="back-to-search">← Back to search</button>'); if (headerContent) { title.hidden = true; route.classList.add('header-booking-route'); headerContent.append(route); } const back = route.querySelector('.back-to-search'); const payment = document.querySelector('.issue-ticket'); if (back && payment && !document.querySelector('.booking-actions')) { const actions = document.createElement('div'); actions.className = 'booking-actions'; payment.before(actions); actions.append(back, payment); } }); };
const ensureDocsModal = () => { let modal = document.querySelector('#docs-modal'); if (modal) return modal; modal = document.createElement('dialog'); modal.id = 'docs-modal'; modal.innerHTML = `<form method="dialog" id="docs-form"><button class="close" value="cancel" aria-label="Close">×</button><h2>DOCS import</h2><p class="modal-copy">Paste passenger lines from Amadeus, Galileo, or Sabre. Passenger names will be copied into the form for review.</p><textarea id="docs-input" placeholder="Example: NM1BATBOLD/BAYAR MR&#10;or N.BATBOLD/BAYAR"></textarea><div class="docs-actions"><button value="cancel" class="secondary">Cancel</button><button class="primary" value="import">Import passengers</button></div></form>`; document.body.append(modal); modal.querySelector('form').addEventListener('submit', event => { event.preventDefault(); if (event.submitter?.value === 'cancel') return modal.close(); const names = modal.querySelector('#docs-input').value.split(/\r?\n/).map(line => line.match(/(?:NM\d*|N\.|-\d*)?\s*([A-Z][A-Z' -]+)\/([A-Z][A-Z' -]+)/i)).filter(Boolean).map(match => ({ last: match[1].trim(), first: match[2].replace(/\b(MR|MRS|MS|MISS|CHD|INF)\b/ig, '').trim() })); document.querySelectorAll('.passenger-card').forEach((card, index) => { const name = names[index]; const fields = card.querySelectorAll('input'); if (name && fields.length > 1) { fields[0].value = name.last; fields[1].value = name.first; } }); modal.close(); showToast(names.length ? `${names.length} passenger name(s) imported. Please review all details.` : 'No passenger names found. Check the DOCS format.'); }); return modal; };
const openBookingScreen = () => { document.body.classList.add('booking-mode'); const checkout = resultArea.querySelector('.passenger-checkout'); if (!checkout || checkout.querySelector('.booking-route')) return; const route = `${selectedOutbound?.departure?.id || ''} <i>↔</i> ${selectedOutbound?.arrival?.id || ''}`; checkout.insertAdjacentHTML('afterbegin', `<div class="booking-route"><span>${selectedReturn ? 'Round trip' : 'One way'}</span><h1>${route}</h1></div>`); checkout.querySelector('.checkout-heading').insertAdjacentHTML('afterend', `<div class="booking-service"><strong>Booking code selected · Economy</strong><button class="docs-import" type="button">DOCS import</button></div>`); };
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair')) openBookingScreen(); if (event.target.closest('.docs-import')) ensureDocsModal().showModal(); if (event.target.closest('[data-view="search"]')) document.body.classList.remove('booking-mode'); });
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair')) queueMicrotask(() => { const route = document.querySelector('.booking-route'); if (route && !route.querySelector('.back-to-search')) route.insertAdjacentHTML('beforeend', '<button type="button" class="back-to-search">← Back to search</button>'); }); if (event.target.closest('.back-to-search')) { document.body.classList.remove('booking-mode'); resultArea.classList.add('hidden'); resultArea.innerHTML = ''; selectedOutbound = null; selectedReturn = null; document.querySelector('#search').scrollIntoView({ behavior: 'smooth', block: 'start' }); } });
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair')) queueMicrotask(() => { const route = document.querySelector('.booking-route'); const headerContent = document.querySelector('main > header > div'); const title = document.querySelector('#page-title'); if (route && headerContent) { title.hidden = true; route.classList.add('header-booking-route'); headerContent.append(route); } }); if (event.target.closest('.back-to-search') || event.target.closest('[data-view="search"]')) document.querySelector('#page-title').hidden = false; });
document.addEventListener('click', event => { if (!event.target.closest('.select-round-pair')) return; queueMicrotask(() => { const back = document.querySelector('.back-to-search'); const payment = document.querySelector('.issue-ticket'); if (!back || !payment || document.querySelector('.booking-actions')) return; const actions = document.createElement('div'); actions.className = 'booking-actions'; payment.before(actions); actions.append(back, payment); }); });
document.addEventListener('click', event => { if (event.target.closest('.back-to-search') || event.target.closest('[data-view="search"]')) document.querySelectorAll('.header-booking-route').forEach(route => route.remove()); });
const returnSearchQuery = flight => new URLSearchParams({ departureToken: flight.departureToken, airline: flight.airlineCode || '', departure: airportCode(document.querySelector('#departure').value), arrival: airportCode(document.querySelector('#arrival').value), date: document.querySelector('#outbound-date').value, returnDate: document.querySelector('#return-date').value, adults: document.querySelector('#adults').value, children: document.querySelector('#children').value, infants: document.querySelector('#infants').value });
const getReturnFlights = async flight => { if (!flight.departureToken) return null; const response = await fetch(`/api/flights?${returnSearchQuery(flight)}`); const data = await response.json(); return response.ok && data.results?.length ? { flight: data.results[0], sameAirline: data.sameAirline } : null; };
const connectionDuration = (arrivalTime, departureTime) => { const toMinutes = value => { const matched = String(value || '').match(/(\d{1,2}):(\d{2})/); return matched ? Number(matched[1]) * 60 + Number(matched[2]) : null; }; const arrival = toMinutes(arrivalTime); const departure = toMinutes(departureTime); if (arrival === null || departure === null) return 'Connection'; const wait = (departure - arrival + 1440) % 1440; return wait ? `Connection · ${formatMinutes(wait)} layover` : 'Connection'; };
const segmentDetail = (flight, detailId) => { const segments = flight.segments?.length ? flight.segments : [flight]; const first = segments[0]; const last = segments.at(-1); return `<div id="${detailId}" class="segment-details" hidden><div class="detail-route"><strong>${first.departure?.id || ''} <i>→</i> ${last.arrival?.id || ''}</strong><span>${segments.length > 1 ? `${segments.length - 1} connection${segments.length > 2 ? 's' : ''}` : 'Direct flight'}</span></div>${segments.map((segment, index) => `<div class="segment-detail"><div class="segment-carrier"><i>${segment.airlineLogo ? `<img src="${segment.airlineLogo}" alt="" onerror="this.remove()" />` : '✈'}</i><span>${segment.airline || flight.airline} · ${segment.number || 'Flight'}</span></div><div class="segment-point"><small>DEPARTURE</small><strong>${(segment.departure?.time || '').slice(-5)} <em>${segment.departure?.id || ''}</em></strong><span>${segment.departure?.name || ''}</span></div><div class="segment-line"><b>${segment.duration ? formatMinutes(segment.duration) : 'Flight'}</b><i></i><span>Nonstop</span></div><div class="segment-point"><small>ARRIVAL</small><strong>${(segment.arrival?.time || '').slice(-5)} <em>${segment.arrival?.id || ''}</em></strong><span>${segment.arrival?.name || ''}</span></div><div class="segment-meta">${[segment.airplane, segment.travelClass].filter(Boolean).join(' · ') || 'Flight information'}</div>${index < segments.length - 1 ? `<div class="connection-note">${connectionDuration(segment.arrival?.time, segments[index + 1].departure?.time)}</div>` : ''}</div>`).join('')}</div>`; };
const searchRow = (flight, label, detailId) => `<div class="round-leg"><span>${label}</span><div class="round-airline"><i>${flight.airlineLogo ? `<img src="${flight.airlineLogo}" alt="${flight.airline} logo" onerror="this.remove()" />` : '✈'}</i><div><strong>${flight.airline}</strong><small>${flight.number || 'Flight'} · ${timeText(flight)}</small></div></div><button type="button" class="segment-toggle" data-detail-id="${detailId}" aria-expanded="false" aria-label="Show flight details">⌄</button></div>${segmentDetail(flight, detailId)}`;
const pairTotal = pair => { const raw = [pair.outbound.price, pair.returnFlight.price]; if (raw.some(value => !String(value ?? '').match(/\d/))) return 'Price unavailable'; const values = raw.map(value => Number(String(value).replace(/[^\d.]/g, ''))); return values.every(Number.isFinite) ? `¥ ${values.reduce((a, b) => a + b, 0).toLocaleString('en-US')}` : 'Price unavailable'; };
const renderRoundPairs = pairs => { resultArea.classList.remove('hidden'); resultArea.innerHTML = `<div class="results-head"><h2>Round trip combinations</h2><span>Departure and arrival flights shown together</span></div>${pairs.length ? pairs.map((pair, index) => `<article class="round-pair">${searchRow(pair.outbound, 'DEPARTURE', `departure-detail-${index}`)}${searchRow(pair.returnFlight, 'ARRIVAL', `arrival-detail-${index}`)}<div class="pair-footer"><span>${pair.sameAirline ? 'Same airline return' : 'Alternative airline return'}</span><strong>${pairTotal(pair)}</strong><button class="primary select-round-pair" data-pair-index="${index}">Select itinerary</button></div></article>`).join('') : '<div class="no-results">No return combinations were found for the first outbound options.</div>'}`; document.querySelectorAll('.segment-toggle').forEach(button => button.addEventListener('click', () => { const detail = document.querySelector(`#${button.dataset.detailId}`); const open = detail.hidden; detail.hidden = !open; button.textContent = open ? '⌃' : '⌄'; button.setAttribute('aria-expanded', String(open)); })); document.querySelectorAll('.select-round-pair').forEach(button => button.addEventListener('click', () => { const pair = pairs[Number(button.dataset.pairIndex)]; selectedOutbound = pair.outbound; selectedReturn = pair.returnFlight; showItinerary(); })); };
const loadRoundPairs = async outboundFlights => { resultArea.classList.remove('hidden'); resultArea.innerHTML = '<div class="no-results"><strong>Building round trip combinations...</strong><br>Searching return flights for the best outbound options.</div>'; const shortlisted = outboundFlights.filter(flight => flight.departureToken).slice(0, 3); const resolved = await Promise.all(shortlisted.map(async outbound => { try { const returned = await getReturnFlights(outbound); return returned ? { outbound, returnFlight: returned.flight, sameAirline: returned.sameAirline } : null; } catch { return null; } })); renderRoundPairs(resolved.filter(Boolean)); };
const bindFlightButtons = () => document.querySelectorAll('.book-flight').forEach(b => b.addEventListener('click', () => selectFlight(visibleFlights[Number(b.dataset.index)])));
const renderFlights = (results, phase = 'outbound', sameAirline = true) => {
  visibleFlights = results; searchPhase = phase;
  resultArea.classList.remove('hidden');
  const flights = results.map((f, i) => `<article class="flight"><div class="carrier"><span class="plane">${f.airlineLogo ? `<img src="${f.airlineLogo}" alt="${f.airline} logo" onerror="this.remove()" />` : '✈'}</span><div><strong>${f.airline}</strong><small>${f.number || 'Flight'} · Economy</small></div></div><div class="flight-time"><strong>${(f.departure.time || '').slice(-5)}</strong><span>${f.departure.id || ''}</span></div><div class="duration">${formatMinutes(f.duration || 0)} <i></i><small>${f.stops ? `${f.stops} stop${f.stops > 1 ? 's' : ''}` : 'Nonstop'}</small></div><div class="flight-time"><strong>${(f.arrival.time || '').slice(-5)}</strong><span>${f.arrival.id || ''}</span></div><div class="fare"><small>FROM</small><strong>${priceText(f.price)}</strong><span>per adult</span></div><button class="primary book-flight" data-index="${i}">Select</button></article>`).join('');
  const heading = phase === 'return' ? 'Choose return flight' : 'Choose outbound flight'; const note = phase === 'return' ? (sameAirline ? 'Same airline options' : 'Same airline unavailable · alternative airlines shown') : 'Live search · SerpApi / Google Flights';
  resultArea.innerHTML = `${phase === 'return' ? selectedOutboundPanel() : ''}<div class="results-head"><h2>${heading}</h2><span>${note}</span></div>${flights || '<div class="no-results">No flights found for this route and date.</div>'}`;
  bindFlightButtons();
};
async function selectFlight(flight) {
  if (tripType !== 'round') { selectedOutbound = flight; selectedReturn = null; return prepareBookingScreen(); }
  if (searchPhase === 'return') { selectedReturn = flight; return prepareBookingScreen(); }
  selectedOutbound = flight;
  if (!flight?.departureToken) { resultArea.innerHTML = '<div class="no-results"><strong>Return flight cannot be loaded.</strong><br>The flight provider did not return a departure token for this option.</div>'; return; }
  resultArea.innerHTML = '<div class="no-results"><strong>Searching return flights...</strong></div>';
  const query = returnSearchQuery(flight);
  try { const response = await fetch(`/api/flights?${query}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); renderFlights(data.results, 'return', data.sameAirline); }
  catch (error) { resultArea.innerHTML = `<div class="no-results"><strong>Return search is unavailable.</strong><br>${error.message || 'Please try again later.'}</div>`; }
}
document.querySelectorAll('[data-trip]').forEach(button => button.addEventListener('click', () => { tripType = button.dataset.trip; document.querySelectorAll('[data-trip]').forEach(b => b.classList.toggle('selected', b === button)); document.querySelector('.return-date').hidden = tripType !== 'round'; resultArea.classList.add('hidden'); }));
const passengerLimits = { adults: { min: 1, max: 9 }, children: { min: 0, max: 8 }, infants: { min: 0, max: 8 } };
document.querySelectorAll('[data-change]').forEach(button => button.addEventListener('click', () => {
  const field = button.dataset.change; const input = document.querySelector(`#${field}`); const limit = passengerLimits[field];
  const next = Math.min(limit.max, Math.max(limit.min, Number(input.value) + Number(button.dataset.step)));
  input.value = next; document.querySelector(`#${field}-output`).value = next;
  if (field === 'adults' && next === 1 && Number(button.dataset.step) < 0) toast('At least one adult is required when travelling with children or infants.');
}));
const outboundDateInput = document.querySelector('#outbound-date'); const returnDateInput = document.querySelector('#return-date');
const isoDate = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const localToday = isoDate(new Date());
if (outboundDateInput.value < localToday) outboundDateInput.value = localToday;
if (returnDateInput.value < outboundDateInput.value) returnDateInput.value = outboundDateInput.value;
outboundDateInput.addEventListener('change', () => { if (returnDateInput.value < outboundDateInput.value) returnDateInput.value = outboundDateInput.value; });
const calendarPopover = document.querySelector('#calendar-popover'); let activeDateInput = null; let calendarMonth = null;
const calendarMinimum = input => input.id === 'outbound-date' ? localToday : (outboundDateInput.value > localToday ? outboundDateInput.value : localToday);
const renderCalendar = () => { const year = calendarMonth.getFullYear(); const month = calendarMonth.getMonth(); const first = new Date(year, month, 1); const start = (first.getDay() + 6) % 7; const selected = activeDateInput.value; const minimum = calendarMinimum(activeDateInput); const labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']; const days = Array.from({ length: 42 }, (_, i) => { const date = new Date(year, month, i - start + 1); const dateIso = isoDate(date); const weekend = i % 7 >= 5; return `<button type="button" class="${weekend ? 'weekend ' : ''}${date.getMonth() !== month ? 'outside ' : ''}${dateIso === selected ? 'selected' : ''}" data-calendar-date="${dateIso}" ${dateIso < minimum ? 'disabled' : ''}>${date.getDate()}</button>`; }).join(''); calendarPopover.innerHTML = `<div class="calendar-head"><button type="button" data-calendar-nav="-1">‹</button><strong>${calendarMonth.toLocaleString('en-US', { month: 'long', year: 'numeric' })}</strong><button type="button" data-calendar-nav="1">›</button></div><div class="calendar-week">${labels.map((label, index) => `<span class="${index >= 5 ? 'weekend' : ''}">${label}</span>`).join('')}</div><div class="calendar-days">${days}</div>`; calendarPopover.querySelectorAll('[data-calendar-nav]').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); calendarMonth = new Date(year, month + Number(button.dataset.calendarNav), 1); renderCalendar(); })); calendarPopover.querySelectorAll('[data-calendar-date]').forEach(button => button.addEventListener('click', () => { activeDateInput.value = button.dataset.calendarDate; activeDateInput.dispatchEvent(new Event('change')); calendarPopover.hidden = true; })); };
const openCalendar = input => { activeDateInput = input; const [year, month] = input.value.split('-').map(Number); calendarMonth = new Date(year, month - 1, 1); const rect = input.getBoundingClientRect(); calendarPopover.style.top = `${Math.min(rect.bottom + 7, window.innerHeight - 345)}px`; calendarPopover.style.left = `${Math.min(rect.left, window.innerWidth - 320)}px`; calendarPopover.hidden = false; renderCalendar(); };
document.querySelectorAll('.open-calendar').forEach(button => button.addEventListener('click', () => openCalendar(document.querySelector(`#${button.dataset.dateInput}`)))); [outboundDateInput, returnDateInput].forEach(input => input.addEventListener('click', () => openCalendar(input))); document.addEventListener('click', event => { if (!event.target.closest('.calendar-popover') && !event.target.closest('.date-control')) calendarPopover.hidden = true; });
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
const commonAirports = { UBN: 'Ulaanbaatar', PVG: 'Shanghai', SHA: 'Shanghai' };
const offlineLocations = [{ city: 'Ulaanbaatar', code: 'UBN', airport: 'Chinggis Khaan International Airport' }, { city: 'Shanghai', code: 'PVG', airport: 'Pudong International Airport' }, { city: 'Shanghai', code: 'SHA', airport: 'Hongqiao International Airport' }, { city: 'Beijing', code: 'PEK', airport: 'Capital International Airport' }, { city: 'Beijing', code: 'PKX', airport: 'Daxing International Airport' }, { city: 'Hong Kong', code: 'HKG', airport: 'Hong Kong International Airport' }, { city: 'Tokyo', code: 'NRT', airport: 'Narita International Airport' }, { city: 'Seoul', code: 'ICN', airport: 'Incheon International Airport' }];
const setupAirportAutocomplete = (inputId, listId) => {
  const input = document.querySelector(`#${inputId}`); const list = document.querySelector(`#${listId}`); let timer;
  const clear = () => { list.innerHTML = ''; };
  const getOptions = async q => { const local = () => offlineLocations.filter(option => `${option.city} ${option.code} ${option.airport}`.toLowerCase().includes(q.toLowerCase())); try { const response = await fetch(`/api/locations?q=${encodeURIComponent(q)}`); const data = await response.json(); return response.ok ? (data.options ?? []) : local(); } catch { return local(); } };
  const choose = option => { input.value = `${option.city} (${option.code})`; clear(); };
  const lookup = async () => { const q = input.value.trim(); if (q.length < 2) return clear(); try { const options = await getOptions(q); list.innerHTML = options.slice(0, 7).map(option => `<button type="button" class="suggestion" data-code="${escapeHtml(option.code)}" data-city="${escapeHtml(option.city)}"><span><strong>${escapeHtml(option.city)} (${escapeHtml(option.code)})</strong><small>${escapeHtml(option.airport)}</small></span><code>${escapeHtml(option.code)}</code></button>`).join(''); list.querySelectorAll('.suggestion').forEach(button => button.addEventListener('mousedown', event => { event.preventDefault(); choose({ city: button.dataset.city, code: button.dataset.code }); })); } catch { clear(); } };
  input.addEventListener('input', () => { clearTimeout(timer); timer = setTimeout(lookup, 350); }); input.addEventListener('focus', () => { if (input.value.trim().length >= 2) { clearTimeout(timer); timer = setTimeout(lookup, 150); } }); input.addEventListener('blur', () => { const code = input.value.trim().toUpperCase(); if (!/^[A-Z]{3}$/.test(code)) return; setTimeout(async () => { if (input.value.trim().toUpperCase() !== code) return; try { const options = commonAirports[code] ? [{ city: commonAirports[code], code }] : await getOptions(code); const exact = options.find(option => option.code.toUpperCase() === code); if (exact) choose(exact); } catch { clear(); } }, 120); }); document.addEventListener('click', event => { if (!event.target.closest('.autocomplete')) clear(); });
};
setupAirportAutocomplete('departure', 'departure-suggestions'); setupAirportAutocomplete('arrival', 'arrival-suggestions');
document.querySelector('.swap').addEventListener('click', () => { const from = document.querySelector('#departure'); const to = document.querySelector('#arrival'); [from.value, to.value] = [to.value, from.value]; from.focus(); });
document.querySelector('#search-form').addEventListener('submit', async e => {
  e.preventDefault(); const button = e.currentTarget.querySelector('.primary'); const departureInput = document.querySelector('#departure'); const arrivalInput = document.querySelector('#arrival');
  const departure = departureInput.value.match(/\(([A-Z]{3})\)/)?.[1] || departureInput.value.trim(); const arrival = arrivalInput.value.match(/\(([A-Z]{3})\)/)?.[1] || arrivalInput.value.trim();
  selectedOutbound = null; selectedReturn = null; button.disabled = true; button.textContent = 'Searching…';
  try { const query = new URLSearchParams({ departure, arrival, date: document.querySelector('#outbound-date').value, returnDate: document.querySelector('#return-date').value, adults: document.querySelector('#adults').value, children: document.querySelector('#children').value, infants: document.querySelector('#infants').value, trip: tripType }); const response = await fetch(`/api/flights?${query}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (tripType === 'round') await loadRoundPairs(data.results); else renderFlights(data.results, 'outbound'); }
  catch (error) { showMockSearch(departure, arrival); }
  finally { button.disabled = false; button.textContent = 'Search flights'; }
});
bindFlightButtons();
const topup = document.querySelector('#topup-modal'); topup.querySelector('.close').addEventListener('click', () => topup.close());
const toast = message => { const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3400); };
const portalSession = () => JSON.parse(sessionStorage.getItem('flightb2b-session') || '{}');
const secureFetch = async (url, options = {}) => fetch(url, { ...options, headers: { authorization: `Bearer ${portalSession().accessToken}`, ...(options.headers || {}) } });
const cny = value => `¥ ${Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
const loadPricingRate = async () => { const preview = document.querySelector('#topup-rate-preview'); try { const response = await fetch('/api/fx/cny-mnt'); const rate = await response.json(); if (!response.ok) throw new Error(rate.error); pricingRate = rate; if (preview) preview.textContent = 'Enter a wallet-credit amount to calculate the MNT invoice.'; const amount = document.querySelector('#topup-amount'); const update = () => { if (preview && Number(amount.value) > 0) preview.textContent = `Invoice payable: ${mnt(Number(amount.value) * rate.effectiveRateMnt)}`; }; amount?.addEventListener('input', update); } catch (error) { if (preview) preview.textContent = error.message || 'Exchange rate is temporarily unavailable.'; } };
const downloadInvoice = async (id, number) => { const response = await secureFetch(`/api/invoices/${id}`); if (!response.ok) return toast('Invoice download failed.'); const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${number}.html`; link.click(); URL.revokeObjectURL(link.href); };
const loadTopupInvoices = async () => { const target = document.querySelector('#topup-invoices'); if (!target || !portalSession().accessToken) return; try { const response = await secureFetch('/api/topups'); const rows = await response.json(); if (!response.ok) throw new Error(rows.error); const pending = rows.filter(item => item.status === 'pending').reduce((sum, item) => sum + Number(item.amount_mnt || 0), 0); const total = document.querySelector('#pending-topups'); if (total) total.textContent = mnt(pending); target.innerHTML = rows.map(item => `<tr><td><strong>${item.invoice_number}</strong></td><td>${new Date(item.created_at).toLocaleDateString('en-GB')}</td><td><strong>${mnt(item.amount_mnt)}</strong><small>Wallet: ${cny(item.amount_cny)}</small></td><td><span class="tag ${item.status === 'approved' ? 'ticketed' : 'pending'}">${item.status}</span></td><td><button class="text-btn download-invoice" data-invoice-id="${item.id}" data-invoice-number="${item.invoice_number}">Download</button>${item.status === 'pending' ? `<button class="text-btn delete-invoice" data-invoice-id="${item.id}">Delete</button>` : ''}</td></tr>`).join('') || '<tr><td colspan="5" class="no-bookings">No top-up invoices yet.</td></tr>'; } catch { target.innerHTML = '<tr><td colspan="5" class="no-bookings">Unable to load invoices.</td></tr>'; } };
document.querySelectorAll('[data-open-topup]').forEach(b=>b.addEventListener('click',()=>topup.showModal()));
document.querySelector('#topup-form').addEventListener('submit', async e=>{ e.preventDefault(); const error = document.querySelector('#topup-error'); const submit = e.target.querySelector('.primary'); error.hidden = true; submit.disabled = true; try { const form = Object.fromEntries(new FormData(e.target)); const response = await secureFetch('/api/topups', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); topup.close(); e.target.reset(); await loadTopupInvoices(); toast(`Invoice ${result.invoice.invoice_number} created.`); downloadInvoice(result.invoice.id, result.invoice.invoice_number); } catch (issue) { error.textContent = issue.message; error.hidden = false; } finally { submit.disabled = false; } });
document.addEventListener('click', async event => { const download = event.target.closest('.download-invoice'); if (download) return downloadInvoice(download.dataset.invoiceId, download.dataset.invoiceNumber); const remove = event.target.closest('.delete-invoice'); if (!remove || !confirm('Delete this pending invoice?')) return; const response = await secureFetch(`/api/topups/${remove.dataset.invoiceId}`, { method: 'DELETE' }); const result = await response.json(); if (!response.ok) return toast(result.error || 'Invoice could not be deleted.'); await loadTopupInvoices(); toast('Pending invoice deleted.'); });
window.loadTopupInvoices = loadTopupInvoices;
loadPricingRate();
loadTopupInvoices();
