const bookings = [
  { ref: 'BM7K2Q', route: 'ULN → PVG', passenger: 'BATBOLD / ENKHTAIVAN', issued: '05 Aug 2026', total: '¥ 1,280.00', status: 'Ticketed' },
  { ref: 'K8M4RP', route: 'PVG → ULN', passenger: 'DULAM / SARUUL', issued: '04 Aug 2026', total: '¥ 1,460.00', status: 'Ticketed' },
  { ref: 'QF9A2N', route: 'ULN → SHA', passenger: 'ERDENE / TUMUR', issued: '04 Aug 2026', total: '¥ 1,350.00', status: 'Pending' },
  { ref: 'L3Y7CX', route: 'PVG → ULN', passenger: 'MUNKH / NARAN', issued: '02 Aug 2026', total: '¥ 1,290.00', status: 'Ticketed' }
];
const ledger = [
  ['05 Aug 2026, 09:42', 'TKT-BM7K2Q', 'Ticket issue · ULN → PVG', 'Debit', '− ¥ 1,280.00', '¥ 12,480.00'],
  ['04 Aug 2026, 15:18', 'TKT-K8M4RP', 'Ticket issue · PVG → ULN', 'Debit', '− ¥ 1,460.00', '¥ 13,760.00'],
  ['01 Aug 2026, 11:05', 'TOP-10681', 'Top-up approved by finance', 'Credit', '+ ¥ 15,000.00', '¥ 15,220.00'],
  ['31 Jul 2026, 16:34', 'TKT-L3Y7CX', 'Ticket issue · PVG → ULN', 'Debit', '− ¥ 1,290.00', '¥ 220.00']
];
const bookingRows = (withAction = false) => bookings.map(b => `<tr><td><strong>${b.ref}</strong></td><td>${b.route}</td><td>${b.passenger}</td><td>${b.issued}</td><td><strong>${b.total}</strong></td><td><span class="tag ${b.status.toLowerCase()}">${b.status}</span></td>${withAction ? '<td><button class="text-btn">View</button></td>' : ''}</tr>`).join('');
document.querySelector('#recent-bookings').innerHTML = bookingRows();
document.querySelector('#all-bookings').innerHTML = bookingRows(true);
document.querySelector('#ledger').innerHTML = ledger.map(row => `<tr>${row.map((x,i)=> `<td class="${i===3 ? (x === 'Credit' ? 'credit' : 'debit') : ''}">${x}</td>`).join('')}</tr>`).join('');
const showView = id => { document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id)); document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id)); document.querySelector('#page-title').textContent = id==='dashboard' ? 'Good morning, Bayar' : id==='search' ? 'Flight search' : id[0].toUpperCase()+id.slice(1); window.scrollTo({top:0,behavior:'smooth'}); };
document.querySelectorAll('[data-view], [data-view-target]').forEach(btn => btn.addEventListener('click', () => showView(btn.dataset.view || btn.dataset.viewTarget)));
const formatMinutes = minutes => `${Math.floor(minutes / 60)}h ${minutes % 60}m`;
const resultArea = document.querySelector('#flight-results');
let tripType = 'round'; let visibleFlights = []; let searchPhase = 'outbound'; let selectedOutbound = null; let selectedReturn = null;
const priceText = price => price ? (String(price).includes('¥') ? price : `¥ ${price}`) : 'Price unavailable';
const timeText = flight => `${(flight.departure.time || '').slice(-5)} ${flight.departure.id || ''} → ${(flight.arrival.time || '').slice(-5)} ${flight.arrival.id || ''}`;
const flightCard = (flight, label) => `<article class="selection-card"><div class="selection-label">${label}</div><div class="selection-main"><div><strong>${flight.airline}</strong><span>${flight.number || 'Flight'} · ${timeText(flight)}</span></div><div class="selection-duration">${formatMinutes(flight.duration || 0)} · ${flight.stops ? `${flight.stops} stop${flight.stops > 1 ? 's' : ''}` : 'Nonstop'}</div><b>${priceText(flight.price)}</b></div></article>`;
const selectedOutboundPanel = () => selectedOutbound ? `<section class="selected-itinerary"><div class="selected-title"><span>✓</span><div><h2>Outbound flight selected</h2><p>Select your return flight below.</p></div></div>${flightCard(selectedOutbound, 'OUTBOUND')}</section>` : '';
const totalPrice = () => { const numbers = [selectedOutbound, selectedReturn].map(f => Number(String(f?.price ?? '').replace(/[^\d.]/g, ''))).filter(Number.isFinite); return numbers.length ? `¥ ${numbers.reduce((sum, value) => sum + value, 0).toLocaleString('en-US')}` : 'Price unavailable'; };
const airportNames = { UBN: 'Chinggis Khaan International Airport', ULN: 'Chinggis Khaan International Airport', PVG: 'Shanghai Pudong International Airport', SHA: 'Shanghai Hongqiao International Airport', PEK: 'Beijing Capital International Airport', PKX: 'Beijing Daxing International Airport', HKG: 'Hong Kong International Airport', NRT: 'Tokyo Narita International Airport', ICN: 'Seoul Incheon International Airport' };
const mockFlight = (departure, arrival, number, departureTime, arrivalTime, price, airline = 'Spring') => ({ airline, number, duration: 250, stops: 0, price: String(price), departure: { id: departure, time: departureTime, name: airportNames[departure] || `${departure} Airport` }, arrival: { id: arrival, time: arrivalTime, name: airportNames[arrival] || `${arrival} Airport` }, segments: [{ airline, number, duration: 250, departure: { id: departure, time: departureTime, name: airportNames[departure] || `${departure} Airport` }, arrival: { id: arrival, time: arrivalTime, name: airportNames[arrival] || `${arrival} Airport` }, airplane: 'Airbus A320', travelClass: 'Economy' }] });
const mockSearchResults = (departure, arrival) => [mockFlight(departure, arrival, '9C 7058', '13:00', '17:00', 2095), mockFlight(departure, arrival, '9C 7012', '08:10', '12:05', 2360), mockFlight(departure, arrival, '9C 7026', '18:30', '22:30', 2580)];
const showMockSearch = (departure, arrival) => { const outbound = mockSearchResults(departure, arrival); if (tripType === 'round') { const returns = [mockFlight(arrival, departure, '9C 7057', '08:10', '12:00', 1960), mockFlight(arrival, departure, '9C 7011', '14:15', '18:05', 2150), mockFlight(arrival, departure, '9C 7025', '19:20', '23:15', 2290)]; renderRoundPairs(outbound.map((flight, index) => ({ outbound: flight, returnFlight: returns[index], sameAirline: true }))); } else renderFlights(outbound, 'outbound'); };
const showItinerary = () => { resultArea.classList.remove('hidden'); resultArea.innerHTML = `<section class="final-itinerary"><div class="selected-title"><span>✓</span><div><p class="eyebrow">ROUND TRIP SELECTED</p><h2>Your selected itinerary</h2></div></div>${flightCard(selectedOutbound, 'OUTBOUND')} ${flightCard(selectedReturn, 'RETURN')}<div class="fare-total"><span>Total fare for selected flights</span><strong>${totalPrice()}</strong></div><button class="primary continue-ticket">Continue to passenger details</button></section>`; document.querySelector('.continue-ticket').addEventListener('click', () => document.querySelector('#ticket-modal').showModal()); };
const checkoutFlight = (flight, label) => flight ? `<article class="checkout-flight"><div><span class="journey-tag ${label.toLowerCase()}">${label}</span><b>${flight.airline || 'Airline'} ${flight.number || ''}</b></div><div class="checkout-times"><strong>${(flight.departure?.time || '').slice(-5)}</strong><i></i><strong>${(flight.arrival?.time || '').slice(-5)}</strong></div><div class="checkout-airports"><span>${flight.departure?.name || flight.departure?.id || ''} (${flight.departure?.id || ''})</span><span>${flight.arrival?.name || flight.arrival?.id || ''} (${flight.arrival?.id || ''})</span></div></article>` : '';
const passengerForm = (type, index) => `<section class="passenger-card"><div class="passenger-card-title"><h2>${index + 1} ${type}</h2></div><div class="passenger-fields"><label>Last name<input required placeholder="As shown on document" /></label><label>First name<input required placeholder="First and middle names" /></label><label>Date of birth<input type="date" required /></label><label>Document type<select><option>Passport</option><option>National ID</option></select></label><label>Document number<input required /></label><label>Issuing country / region<input required placeholder="e.g. Mongolia" /></label><label>Document expiry<input type="date" required /></label><label>Nationality / region<input required placeholder="e.g. Mongolia" /></label><label>Gender<select required><option value="">Select</option><option>Male</option><option>Female</option></select></label></div></section>`;
const showCheckout = () => { const counts = [['Adult', Number(document.querySelector('#adults').value)], ['Child', Number(document.querySelector('#children').value)], ['Infant', Number(document.querySelector('#infants').value)]]; const passengers = counts.flatMap(([type, count]) => Array.from({ length: count }, (_, index) => passengerForm(type, index))); resultArea.classList.remove('hidden'); resultArea.innerHTML = `<section class="passenger-checkout"><div class="checkout-main"><div class="checkout-heading"><p class="eyebrow">PASSENGER DETAILS</p><h2>Enter passenger information</h2><p>Names must match the travel document exactly.</p></div><form id="passenger-form">${passengers.join('')}<section class="contact-card"><h2>Contact person</h2><div class="passenger-fields"><label>Full name<input required /></label><label>Contact number<input type="tel" required /></label><label>Email address<input type="email" required /></label></div><p>Booking confirmation and schedule changes will be sent to this contact.</p></section><button class="primary issue-ticket" type="submit">Continue to payment</button></form></div><aside class="order-summary"><h2>Order details</h2>${checkoutFlight(selectedOutbound, 'Departure')}${checkoutFlight(selectedReturn, 'Arrival')}<div class="summary-total"><span>Total fare</span><strong>${totalPrice()}</strong><small>Final fare and tax are confirmed before ticket issuance.</small></div></aside></section>`; document.querySelector('#passenger-form').addEventListener('submit', event => { event.preventDefault(); document.querySelector('#ticket-modal').showModal(); }); resultArea.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair')) showCheckout(); });
const airportCode = value => value.match(/\(([A-Z]{3})\)/i)?.[1] || value.trim().toUpperCase();
const showToast = message => toast(message);
const collapseCountryFields = () => { document.querySelectorAll('.passenger-card').forEach(card => { const labels = [...card.querySelectorAll('label')]; const issuing = labels.find(label => label.textContent.includes('Issuing country')); const nationality = labels.find(label => label.textContent.includes('Nationality')); const visible = nationality?.querySelector('input:not([type="hidden"])'); if (!issuing || !nationality || !visible) return; let hidden = nationality.querySelector('input[type="hidden"][name="issuing-country"]'); if (!hidden) { hidden = document.createElement('input'); hidden.type = 'hidden'; hidden.name = 'issuing-country'; nationality.append(hidden); visible.addEventListener('input', () => { hidden.value = visible.value; }); visible.addEventListener('change', () => { hidden.value = visible.value; }); } const textNode = [...nationality.childNodes].find(node => node.nodeType === Node.TEXT_NODE); if (textNode) textNode.textContent = 'Nationality (country/region)'; hidden.value = visible.value; issuing.remove(); }); };
new MutationObserver(collapseCountryFields).observe(resultArea, { childList: true, subtree: true });
const combineCountryNationality = () => { document.querySelectorAll('.passenger-card').forEach(card => { const labels = [...card.querySelectorAll('label')]; const issuing = labels.find(label => label.textContent.includes('Issuing country')); const nationality = labels.find(label => label.textContent.includes('Nationality')); if (!issuing || !nationality) return; issuing.hidden = true; const textNode = [...nationality.childNodes].find(node => node.nodeType === Node.TEXT_NODE); if (textNode) textNode.textContent = 'Nationality (country/region)'; }); };
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair') || (event.target.closest('.book-flight') && tripType !== 'round')) setTimeout(combineCountryNationality, 0); });
const allCountryNames = () => { const codes = 'AF AX AL DZ AS AD AO AI AQ AG AR AM AW AU AT AZ BS BH BD BB BY BE BZ BJ BM BT BO BQ BA BW BV BR IO BN BG BF BI CV KH CM CA KY CF TD CL CN CX CC CO KM CG CD CK CR CI HR CU CW CY CZ DK DJ DM DO EC EG SV GQ ER EE SZ ET FK FO FJ FI FR GF PF TF GA GM GE DE GH GI GR GL GD GP GU GT GG GN GW GY HT HM VA HN HK HU IS IN ID IR IQ IE IM IL IT JM JP JE JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MO MG MW MY MV ML MT MQ MR MU YT MX FM MD MC MN ME MS MA MZ MM NA NR NP NL NC NZ NI NE NG NG NU NF MK MP NO OM PK PW PS PA PG PY PE PH PN PL PT PR QA RE RO RU RW BL SH KN LC MF PM VC WS SM ST SA SN RS SC SL SG SX SK SI SB SO ZA GS SS ES LK SD SR SJ SE CH SY TW TJ TZ TH TL TG TK TO TT TN TR TM TC TV UG UA AE GB US UM UY UZ VU VE VN VG VI WF EH YE ZM ZW XK'.split(' '); const names = new Intl.DisplayNames(['en'], { type: 'region' }); return [...new Set(codes.map(code => names.of(code)).filter(name => name && name.length > 2))].sort((a, b) => a.localeCompare(b)); };
const enhanceCountryMenus = () => { const countries = allCountryNames(); const render = (menu, query) => { const matches = countries.filter(country => country.toLowerCase().includes(query.toLowerCase())); let letter = ''; menu.innerHTML = matches.map(country => { const first = country[0].toUpperCase(); const heading = first === letter ? '' : `<div class="country-letter">${first}</div>`; letter = first; return `${heading}<button type="button" data-country="${country}">${country}</button>`; }).join('') || '<div class="country-letter">No matching country</div>'; }; document.querySelectorAll('.passenger-card').forEach(card => { const labels = [...card.querySelectorAll('label')]; ['Issuing country', 'Nationality'].forEach(text => { const label = labels.find(item => item.textContent.includes(text)); const input = label?.querySelector('input'); if (!label || !input || input.dataset.countryMenuBound) return; input.removeAttribute('list'); input.dataset.countryMenuBound = 'true'; const menu = document.createElement('div'); menu.className = 'country-menu'; menu.hidden = true; label.append(menu); const open = () => { render(menu, input.value); menu.hidden = false; }; input.addEventListener('focus', open); input.addEventListener('input', open); menu.addEventListener('click', event => { const option = event.target.closest('[data-country]'); if (!option) return; input.value = option.dataset.country; input.dispatchEvent(new Event('change')); menu.hidden = true; }); document.addEventListener('click', event => { if (!label.contains(event.target)) menu.hidden = true; }); }); }); };
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair') || (event.target.closest('.book-flight') && tripType !== 'round')) queueMicrotask(bindCountryFields); });
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair') || (event.target.closest('.book-flight') && tripType !== 'round')) setTimeout(enhanceCountryMenus, 0); });
const countryNames = ['Mongolia','Russia','China','Japan','South Korea','North Korea','Kazakhstan','United States','United Kingdom','Germany','France','Turkey','Thailand','Singapore','Vietnam','India','Australia','Canada'];
const bindCountryFields = () => { let list = document.querySelector('#country-options'); if (!list) { list = document.createElement('datalist'); list.id = 'country-options'; list.innerHTML = countryNames.map(country => `<option value="${country}"></option>`).join(''); document.body.append(list); } const correctCountry = value => { const query = value.trim().toLowerCase(); return countryNames.find(country => country.toLowerCase().startsWith(query) || query.startsWith(country.toLowerCase())) || value.trim(); }; document.querySelectorAll('.passenger-card').forEach(card => { const labels = [...card.querySelectorAll('label')]; const issuing = labels.find(label => label.textContent.includes('Issuing country'))?.querySelector('input'); const nationality = labels.find(label => label.textContent.includes('Nationality'))?.querySelector('input'); if (!issuing || !nationality || issuing.dataset.countryBound) return; [issuing, nationality].forEach(input => { input.setAttribute('list', 'country-options'); input.setAttribute('autocomplete', 'off'); input.dataset.countryBound = 'true'; }); const mirror = (source, target) => { const country = correctCountry(source.value); if (country) { source.value = country; target.value = country; } }; issuing.addEventListener('change', () => mirror(issuing, nationality)); issuing.addEventListener('blur', () => mirror(issuing, nationality)); nationality.addEventListener('change', () => mirror(nationality, issuing)); nationality.addEventListener('blur', () => mirror(nationality, issuing)); }); };
const prepareBookingScreen = () => { showCheckout(); queueMicrotask(() => { openBookingScreen(); const route = document.querySelector('.booking-route'); const headerContent = document.querySelector('main > header > div'); const title = document.querySelector('#page-title'); if (!route) return; if (!route.querySelector('.back-to-search')) route.insertAdjacentHTML('beforeend', '<button type="button" class="back-to-search">← Back to search</button>'); if (headerContent) { title.hidden = true; route.classList.add('header-booking-route'); headerContent.append(route); } const back = route.querySelector('.back-to-search'); const payment = document.querySelector('.issue-ticket'); if (back && payment && !document.querySelector('.booking-actions')) { const actions = document.createElement('div'); actions.className = 'booking-actions'; payment.before(actions); actions.append(back, payment); } }); };
const ensureDocsModal = () => { let modal = document.querySelector('#docs-modal'); if (modal) return modal; modal = document.createElement('dialog'); modal.id = 'docs-modal'; modal.innerHTML = `<form method="dialog" id="docs-form"><button class="close" value="cancel" aria-label="Close">×</button><h2>DOCS import</h2><p class="modal-copy">Paste passenger lines from Amadeus, Galileo, or Sabre. Passenger names will be copied into the form for review.</p><textarea id="docs-input" placeholder="Example: NM1BATBOLD/BAYAR MR&#10;or N.BATBOLD/BAYAR"></textarea><div class="docs-actions"><button value="cancel" class="secondary">Cancel</button><button class="primary" value="import">Import passengers</button></div></form>`; document.body.append(modal); modal.querySelector('form').addEventListener('submit', event => { event.preventDefault(); if (event.submitter?.value === 'cancel') return modal.close(); const names = modal.querySelector('#docs-input').value.split(/\r?\n/).map(line => line.match(/(?:NM\d*|N\.|-\d*)?\s*([A-Z][A-Z' -]+)\/([A-Z][A-Z' -]+)/i)).filter(Boolean).map(match => ({ last: match[1].trim(), first: match[2].replace(/\b(MR|MRS|MS|MISS|CHD|INF)\b/ig, '').trim() })); document.querySelectorAll('.passenger-card').forEach((card, index) => { const name = names[index]; const fields = card.querySelectorAll('input'); if (name && fields.length > 1) { fields[0].value = name.last; fields[1].value = name.first; } }); modal.close(); showToast(names.length ? `${names.length} passenger name(s) imported. Please review all details.` : 'No passenger names found. Check the DOCS format.'); }); return modal; };
const openBookingScreen = () => { document.body.classList.add('booking-mode'); const checkout = resultArea.querySelector('.passenger-checkout'); if (!checkout || checkout.querySelector('.booking-route')) return; const route = `${selectedOutbound?.departure?.id || ''} <i>↔</i> ${selectedOutbound?.arrival?.id || ''}`; checkout.insertAdjacentHTML('afterbegin', `<div class="booking-route"><span>${selectedReturn ? 'Round trip' : 'One way'}</span><h1>${route}</h1></div>`); checkout.querySelector('.checkout-heading').insertAdjacentHTML('afterend', `<div class="booking-service"><strong>Booking code selected · Economy</strong><button class="docs-import" type="button">DOCS import</button></div>`); };
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair')) openBookingScreen(); if (event.target.closest('.docs-import')) ensureDocsModal().showModal(); if (event.target.closest('[data-view="search"]')) document.body.classList.remove('booking-mode'); });
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair')) queueMicrotask(() => { const route = document.querySelector('.booking-route'); if (route && !route.querySelector('.back-to-search')) route.insertAdjacentHTML('beforeend', '<button type="button" class="back-to-search">← Back to search</button>'); }); if (event.target.closest('.back-to-search')) { document.body.classList.remove('booking-mode'); resultArea.classList.add('hidden'); resultArea.innerHTML = ''; selectedOutbound = null; selectedReturn = null; document.querySelector('#search').scrollIntoView({ behavior: 'smooth', block: 'start' }); } });
document.addEventListener('click', event => { if (event.target.closest('.select-round-pair')) queueMicrotask(() => { const route = document.querySelector('.booking-route'); const headerContent = document.querySelector('main > header > div'); const title = document.querySelector('#page-title'); if (route && headerContent) { title.hidden = true; route.classList.add('header-booking-route'); headerContent.append(route); } }); if (event.target.closest('.back-to-search') || event.target.closest('[data-view="search"]')) document.querySelector('#page-title').hidden = false; });
document.addEventListener('click', event => { if (!event.target.closest('.select-round-pair')) return; queueMicrotask(() => { const back = document.querySelector('.back-to-search'); const payment = document.querySelector('.issue-ticket'); if (!back || !payment || document.querySelector('.booking-actions')) return; const actions = document.createElement('div'); actions.className = 'booking-actions'; payment.before(actions); actions.append(back, payment); }); });
document.addEventListener('click', event => { if (event.target.closest('.back-to-search') || event.target.closest('[data-view="search"]')) document.querySelectorAll('.header-booking-route').forEach(route => route.remove()); });
const returnSearchQuery = flight => new URLSearchParams({ departureToken: flight.departureToken, airline: flight.airlineCode || '', departure: airportCode(document.querySelector('#departure').value), arrival: airportCode(document.querySelector('#arrival').value), date: document.querySelector('#outbound-date').value, returnDate: document.querySelector('#return-date').value, adults: document.querySelector('#adults').value, children: document.querySelector('#children').value, infants: document.querySelector('#infants').value });
const getReturnFlights = async flight => { if (!flight.departureToken) return null; const response = await fetch(`/api/flights?${returnSearchQuery(flight)}`); const data = await response.json(); return response.ok && data.results?.length ? { flight: data.results[0], sameAirline: data.sameAirline } : null; };
const connectionDuration = (arrivalTime, departureTime) => { const toMinutes = value => { const matched = String(value || '').match(/(\d{1,2}):(\d{2})/); return matched ? Number(matched[1]) * 60 + Number(matched[2]) : null; }; const arrival = toMinutes(arrivalTime); const departure = toMinutes(departureTime); if (arrival === null || departure === null) return 'Connection'; const wait = (departure - arrival + 1440) % 1440; return wait ? `Connection · ${formatMinutes(wait)} layover` : 'Connection'; };
const segmentDetail = (flight, detailId) => { const segments = flight.segments?.length ? flight.segments : [flight]; const first = segments[0]; const last = segments.at(-1); return `<div id="${detailId}" class="segment-details" hidden><div class="detail-route"><strong>${first.departure?.id || ''} <i>→</i> ${last.arrival?.id || ''}</strong><span>${segments.length > 1 ? `${segments.length - 1} connection${segments.length > 2 ? 's' : ''}` : 'Direct flight'}</span></div>${segments.map((segment, index) => `<div class="segment-detail"><div class="segment-carrier"><i>${segment.airlineLogo ? `<img src="${segment.airlineLogo}" alt="" onerror="this.remove()" />` : '✈'}</i><span>${segment.airline || flight.airline} · ${segment.number || 'Flight'}</span></div><div class="segment-point"><small>DEPARTURE</small><strong>${(segment.departure?.time || '').slice(-5)} <em>${segment.departure?.id || ''}</em></strong><span>${segment.departure?.name || ''}</span></div><div class="segment-line"><b>${segment.duration ? formatMinutes(segment.duration) : 'Flight'}</b><i></i><span>Nonstop</span></div><div class="segment-point"><small>ARRIVAL</small><strong>${(segment.arrival?.time || '').slice(-5)} <em>${segment.arrival?.id || ''}</em></strong><span>${segment.arrival?.name || ''}</span></div><div class="segment-meta">${[segment.airplane, segment.travelClass].filter(Boolean).join(' · ') || 'Flight information'}</div>${index < segments.length - 1 ? `<div class="connection-note">${connectionDuration(segment.arrival?.time, segments[index + 1].departure?.time)}</div>` : ''}</div>`).join('')}</div>`; };
const searchRow = (flight, label, detailId) => `<div class="round-leg"><span>${label}</span><div class="round-airline"><i>${flight.airlineLogo ? `<img src="${flight.airlineLogo}" alt="${flight.airline} logo" onerror="this.remove()" />` : '✈'}</i><div><strong>${flight.airline}</strong><small>${flight.number || 'Flight'} · ${timeText(flight)}</small></div></div><button type="button" class="segment-toggle" data-detail-id="${detailId}" aria-expanded="false" aria-label="Show flight details">⌄</button></div>${segmentDetail(flight, detailId)}`;
const pairTotal = pair => { const raw = [pair.outbound.price, pair.returnFlight.price]; if (raw.some(value => !String(value ?? '').match(/\d/))) return 'Price unavailable'; const values = raw.map(value => Number(String(value).replace(/[^\d.]/g, ''))); return values.every(Number.isFinite) ? `¥ ${values.reduce((a, b) => a + b, 0).toLocaleString('en-US')}` : 'Price unavailable'; };
const renderRoundPairs = pairs => { resultArea.classList.remove('hidden'); resultArea.innerHTML = `<div class="results-head"><h2>Round trip combinations</h2><span>Departure and arrival flights shown together</span></div>${pairs.length ? pairs.map((pair, index) => `<article class="round-pair">${searchRow(pair.outbound, 'DEPARTURE', `departure-detail-${index}`)}${searchRow(pair.returnFlight, 'ARRIVAL', `arrival-detail-${index}`)}<div class="pair-footer"><span>${pair.sameAirline ? 'Same airline return' : 'Alternative airline return'}</span><strong>${pairTotal(pair)}</strong><button class="primary select-round-pair" data-pair-index="${index}">Select itinerary</button></div></article>`).join('') : '<div class="no-results">No return combinations were found for the first outbound options.</div>'}`; document.querySelectorAll('.segment-toggle').forEach(button => button.addEventListener('click', () => { const detail = document.querySelector(`#${button.dataset.detailId}`); const open = detail.hidden; detail.hidden = !open; button.textContent = open ? '⌃' : '⌄'; button.setAttribute('aria-expanded', String(open)); })); document.querySelectorAll('.select-round-pair').forEach(button => button.addEventListener('click', () => { const pair = pairs[Number(button.dataset.pairIndex)]; selectedOutbound = pair.outbound; selectedReturn = pair.returnFlight; showItinerary(); })); };
const loadRoundPairs = async outboundFlights => { resultArea.classList.remove('hidden'); resultArea.innerHTML = '<div class="no-results"><strong>Building round trip combinations...</strong><br>Searching return flights for the best outbound options.</div>'; const shortlisted = outboundFlights.filter(flight => flight.departureToken).slice(0, 3); const resolved = await Promise.all(shortlisted.map(async outbound => { try { const returned = await getReturnFlights(outbound); return returned ? { outbound, returnFlight: returned.flight, sameAirline: returned.sameAirline } : null; } catch { return null; } })); renderRoundPairs(resolved.filter(Boolean)); };
const bindFlightButtons = () => document.querySelectorAll('.book-flight').forEach(b => b.addEventListener('click', () => selectFlight(visibleFlights[Number(b.dataset.index)])));
const renderFlights = (results, phase = 'outbound', sameAirline = true) => {
  visibleFlights = results; searchPhase = phase;
  resultArea.classList.remove('hidden');
  const flights = results.map((f, i) => `<article class="flight"><div class="carrier"><span class="plane">${f.airlineLogo ? `<img src="${f.airlineLogo}" alt="${f.airline} logo" onerror="this.remove()" />` : '✈'}</span><div><strong>${f.airline}</strong><small>${f.number || 'Flight'} · Economy</small></div></div><div class="flight-time"><strong>${(f.departure.time || '').slice(-5)}</strong><span>${f.departure.id || ''}</span></div><div class="duration">${formatMinutes(f.duration || 0)} <i></i><small>${f.stops ? `${f.stops} stop${f.stops > 1 ? 's' : ''}` : 'Nonstop'}</small></div><div class="flight-time"><strong>${(f.arrival.time || '').slice(-5)}</strong><span>${f.arrival.id || ''}</span></div><div class="fare"><small>FROM</small><strong>${priceText(f.price)}</strong><span>per adult</span></div><button class="primary book-flight" data-index="${i}">Select</button></article>`).join('');
  const heading = phase === 'return' ? 'Choose return flight' : 'Choose outbound flight'; const note = phase === 'return' ? (sameAirline ? 'Same airline options' : 'Same airline unavailable · alternative airlines shown') : 'Live search · SerpApi / Google Flights';
  resultArea.innerHTML = `${phase === 'return' ? selectedOutboundPanel() : ''}<div class="results-head"><h2>${heading}</h2><span>${note}</span></div>${flights || '<div class="no-results">No flights found for this route and date.</div>'}`;
  bindFlightButtons();
};
async function selectFlight(flight) {
  if (tripType !== 'round') { selectedOutbound = flight; selectedReturn = null; return prepareBookingScreen(); }
  if (searchPhase === 'return') { selectedReturn = flight; return prepareBookingScreen(); }
  selectedOutbound = flight;
  if (!flight?.departureToken) { resultArea.innerHTML = '<div class="no-results"><strong>Return flight cannot be loaded.</strong><br>The flight provider did not return a departure token for this option.</div>'; return; }
  resultArea.innerHTML = '<div class="no-results"><strong>Searching return flights...</strong></div>';
  const query = returnSearchQuery(flight);
  try { const response = await fetch(`/api/flights?${query}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); renderFlights(data.results, 'return', data.sameAirline); }
  catch (error) { resultArea.innerHTML = `<div class="no-results"><strong>Return search is unavailable.</strong><br>${error.message || 'Please try again later.'}</div>`; }
}
document.querySelectorAll('[data-trip]').forEach(button => button.addEventListener('click', () => { tripType = button.dataset.trip; document.querySelectorAll('[data-trip]').forEach(b => b.classList.toggle('selected', b === button)); document.querySelector('.return-date').hidden = tripType !== 'round'; resultArea.classList.add('hidden'); }));
const passengerLimits = { adults: { min: 1, max: 9 }, children: { min: 0, max: 8 }, infants: { min: 0, max: 8 } };
document.querySelectorAll('[data-change]').forEach(button => button.addEventListener('click', () => {
  const field = button.dataset.change; const input = document.querySelector(`#${field}`); const limit = passengerLimits[field];
  const next = Math.min(limit.max, Math.max(limit.min, Number(input.value) + Number(button.dataset.step)));
  input.value = next; document.querySelector(`#${field}-output`).value = next;
  if (field === 'adults' && next === 1 && Number(button.dataset.step) < 0) toast('At least one adult is required when travelling with children or infants.');
}));
const outboundDateInput = document.querySelector('#outbound-date'); const returnDateInput = document.querySelector('#return-date');
const isoDate = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const localToday = isoDate(new Date());
if (outboundDateInput.value < localToday) outboundDateInput.value = localToday;
if (returnDateInput.value < outboundDateInput.value) returnDateInput.value = outboundDateInput.value;
outboundDateInput.addEventListener('change', () => { if (returnDateInput.value < outboundDateInput.value) returnDateInput.value = outboundDateInput.value; });
const calendarPopover = document.querySelector('#calendar-popover'); let activeDateInput = null; let calendarMonth = null;
const calendarMinimum = input => input.id === 'outbound-date' ? localToday : (outboundDateInput.value > localToday ? outboundDateInput.value : localToday);
const renderCalendar = () => { const year = calendarMonth.getFullYear(); const month = calendarMonth.getMonth(); const first = new Date(year, month, 1); const start = (first.getDay() + 6) % 7; const selected = activeDateInput.value; const minimum = calendarMinimum(activeDateInput); const labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']; const days = Array.from({ length: 42 }, (_, i) => { const date = new Date(year, month, i - start + 1); const dateIso = isoDate(date); const weekend = i % 7 >= 5; return `<button type="button" class="${weekend ? 'weekend ' : ''}${date.getMonth() !== month ? 'outside ' : ''}${dateIso === selected ? 'selected' : ''}" data-calendar-date="${dateIso}" ${dateIso < minimum ? 'disabled' : ''}>${date.getDate()}</button>`; }).join(''); calendarPopover.innerHTML = `<div class="calendar-head"><button type="button" data-calendar-nav="-1">‹</button><strong>${calendarMonth.toLocaleString('en-US', { month: 'long', year: 'numeric' })}</strong><button type="button" data-calendar-nav="1">›</button></div><div class="calendar-week">${labels.map((label, index) => `<span class="${index >= 5 ? 'weekend' : ''}">${label}</span>`).join('')}</div><div class="calendar-days">${days}</div>`; calendarPopover.querySelectorAll('[data-calendar-nav]').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); calendarMonth = new Date(year, month + Number(button.dataset.calendarNav), 1); renderCalendar(); })); calendarPopover.querySelectorAll('[data-calendar-date]').forEach(button => button.addEventListener('click', () => { activeDateInput.value = button.dataset.calendarDate; activeDateInput.dispatchEvent(new Event('change')); calendarPopover.hidden = true; })); };
const openCalendar = input => { activeDateInput = input; const [year, month] = input.value.split('-').map(Number); calendarMonth = new Date(year, month - 1, 1); const rect = input.getBoundingClientRect(); calendarPopover.style.top = `${Math.min(rect.bottom + 7, window.innerHeight - 345)}px`; calendarPopover.style.left = `${Math.min(rect.left, window.innerWidth - 320)}px`; calendarPopover.hidden = false; renderCalendar(); };
document.querySelectorAll('.open-calendar').forEach(button => button.addEventListener('click', () => openCalendar(document.querySelector(`#${button.dataset.dateInput}`)))); [outboundDateInput, returnDateInput].forEach(input => input.addEventListener('click', () => openCalendar(input))); document.addEventListener('click', event => { if (!event.target.closest('.calendar-popover') && !event.target.closest('.date-control')) calendarPopover.hidden = true; });
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
const commonAirports = { UBN: 'Ulaanbaatar', PVG: 'Shanghai', SHA: 'Shanghai' };
const offlineLocations = [{ city: 'Ulaanbaatar', code: 'UBN', airport: 'Chinggis Khaan International Airport' }, { city: 'Shanghai', code: 'PVG', airport: 'Pudong International Airport' }, { city: 'Shanghai', code: 'SHA', airport: 'Hongqiao International Airport' }, { city: 'Beijing', code: 'PEK', airport: 'Capital International Airport' }, { city: 'Beijing', code: 'PKX', airport: 'Daxing International Airport' }, { city: 'Hong Kong', code: 'HKG', airport: 'Hong Kong International Airport' }, { city: 'Tokyo', code: 'NRT', airport: 'Narita International Airport' }, { city: 'Seoul', code: 'ICN', airport: 'Incheon International Airport' }];
const setupAirportAutocomplete = (inputId, listId) => {
  const input = document.querySelector(`#${inputId}`); const list = document.querySelector(`#${listId}`); let timer;
  const clear = () => { list.innerHTML = ''; };
  const getOptions = async q => { const local = () => offlineLocations.filter(option => `${option.city} ${option.code} ${option.airport}`.toLowerCase().includes(q.toLowerCase())); try { const response = await fetch(`/api/locations?q=${encodeURIComponent(q)}`); const data = await response.json(); return response.ok ? (data.options ?? []) : local(); } catch { return local(); } };
  const choose = option => { input.value = `${option.city} (${option.code})`; clear(); };
  const lookup = async () => { const q = input.value.trim(); if (q.length < 2) return clear(); try { const options = await getOptions(q); list.innerHTML = options.slice(0, 7).map(option => `<button type="button" class="suggestion" data-code="${escapeHtml(option.code)}" data-city="${escapeHtml(option.city)}"><span><strong>${escapeHtml(option.city)} (${escapeHtml(option.code)})</strong><small>${escapeHtml(option.airport)}</small></span><code>${escapeHtml(option.code)}</code></button>`).join(''); list.querySelectorAll('.suggestion').forEach(button => button.addEventListener('mousedown', event => { event.preventDefault(); choose({ city: button.dataset.city, code: button.dataset.code }); })); } catch { clear(); } };
  input.addEventListener('input', () => { clearTimeout(timer); timer = setTimeout(lookup, 350); }); input.addEventListener('focus', () => { if (input.value.trim().length >= 2) { clearTimeout(timer); timer = setTimeout(lookup, 150); } }); input.addEventListener('blur', () => { const code = input.value.trim().toUpperCase(); if (!/^[A-Z]{3}$/.test(code)) return; setTimeout(async () => { if (input.value.trim().toUpperCase() !== code) return; try { const options = commonAirports[code] ? [{ city: commonAirports[code], code }] : await getOptions(code); const exact = options.find(option => option.code.toUpperCase() === code); if (exact) choose(exact); } catch { clear(); } }, 120); }); document.addEventListener('click', event => { if (!event.target.closest('.autocomplete')) clear(); });
};
setupAirportAutocomplete('departure', 'departure-suggestions'); setupAirportAutocomplete('arrival', 'arrival-suggestions');
document.querySelector('.swap').addEventListener('click', () => { const from = document.querySelector('#departure'); const to = document.querySelector('#arrival'); [from.value, to.value] = [to.value, from.value]; from.focus(); });
document.querySelector('#search-form').addEventListener('submit', async e => {
  e.preventDefault(); const button = e.currentTarget.querySelector('.primary'); const departureInput = document.querySelector('#departure'); const arrivalInput = document.querySelector('#arrival');
  const departure = departureInput.value.match(/\(([A-Z]{3})\)/)?.[1] || departureInput.value.trim(); const arrival = arrivalInput.value.match(/\(([A-Z]{3})\)/)?.[1] || arrivalInput.value.trim();
  selectedOutbound = null; selectedReturn = null; button.disabled = true; button.textContent = 'Searching…';
  try { const query = new URLSearchParams({ departure, arrival, date: document.querySelector('#outbound-date').value, returnDate: document.querySelector('#return-date').value, adults: document.querySelector('#adults').value, children: document.querySelector('#children').value, infants: document.querySelector('#infants').value, trip: tripType }); const response = await fetch(`/api/flights?${query}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (tripType === 'round') await loadRoundPairs(data.results); else renderFlights(data.results, 'outbound'); }
  catch (error) { showMockSearch(departure, arrival); }
  finally { button.disabled = false; button.textContent = 'Search flights'; }
});
bindFlightButtons();
const topup = document.querySelector('#topup-modal'); document.querySelectorAll('[data-open-topup]').forEach(b=>b.addEventListener('click',()=>topup.showModal()));
const toast = message => { const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3400); };
document.querySelector('#topup-form').addEventListener('submit', e=>{ e.preventDefault(); topup.close(); e.target.reset(); toast('Top-up request submitted for finance review.'); });
