import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Build an empty-project installer, not a production migration or a data dump.
export const migrations = [
  'schema.sql', 'admin-functions.sql', 'topups.sql', 'mnt-pricing.sql',
  'topup-expiry.sql', 'topup-wallet-credit-fix.sql', 'topup-bank-transfer-fees.sql',
  'remove-topup-expiry.sql', 'wallet-funding-controls.sql', 'change-wallet-payment.sql',
  'agency-contact-details.sql', 'agent-contact-details.sql', 'spring-status-sync.sql',
  'security-hardening.sql'
];
const readMigration = name => readFileSync(new URL(`../../supabase/${name}`, import.meta.url), 'utf8');
export function buildSchema(readSource = readMigration) {
  const guard = `-- TEST PROJECT ONLY. Generated by deploy/staging/build-schema.mjs.
-- Refuses databases with existing public tables or authentication users.
-- No production business data, credentials or users are included.
begin;
do $$
begin
  if exists (select 1 from pg_tables where schemaname = 'public')
     or exists (select 1 from auth.users) then
    raise exception 'STOP: this installer requires an EMPTY TEST Supabase project.';
  end if;
end $$;
`;
  const body = migrations.map(name => {
    // Normalize before matching. \s also consumes newlines, so the old
    // expression removed different blank lines in LF and CRLF checkouts.
    const sql = readSource(name).replace(/\r\n?/g, '\n')
      .replace(/^[\t ]*(?:begin|commit);[\t ]*(?:\n|$)/gim, '');
    return `\n-- SOURCE: supabase/${name}\n${sql}`;
  }).join('\n');
  return guard + body + '\ncommit;\n';
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(new URL('./empty-test-schema.sql', import.meta.url), buildSchema());
  console.log('Built deploy/staging/empty-test-schema.sql (empty TEST project only).');
}
