-- TEST PROJECT ONLY. Generated by deploy/staging/build-schema.mjs.
-- Refuses databases with existing public tables or authentication users.
-- No production business data, credentials or users are included.
begin;
do $$
begin
  if exists (select 1 from pg_tables where schemaname = 'public')
     or exists (select 1 from auth.users) then
    raise exception 'STOP: this installer requires an EMPTY TEST Supabase project.';
  end if;
end $$;

-- SOURCE: supabase/schema.sql
-- Run in Supabase SQL Editor after creating the project.
create type public.user_role as enum ('agent', 'office_manager', 'platform_admin');
create type public.wallet_entry_type as enum ('credit', 'debit', 'adjustment');

create table public.agencies (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  registration_number text,
  email text,
  phone text,
  address text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.branches (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (agency_id, name)
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  agency_id uuid references public.agencies(id),
  branch_id uuid references public.branches(id),
  role public.user_role not null default 'agent',
  full_name text not null,
  email text,
  phone text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check ((role = 'platform_admin') or agency_id is not null)
);

create table public.wallets (
  agency_id uuid primary key references public.agencies(id) on delete cascade,
  balance_cny numeric(14,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table public.wallet_transactions (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id),
  entry_type public.wallet_entry_type not null,
  amount_cny numeric(14,2) not null check (amount_cny <> 0),
  booking_id uuid,
  reason text not null,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  pnr text unique,
  agency_id uuid not null references public.agencies(id),
  branch_id uuid references public.branches(id),
  created_by uuid not null references public.profiles(id),
  status text not null default 'draft',
  total_cny numeric(14,2) not null check (total_cny >= 0),
  itinerary jsonb not null,
  passengers jsonb not null,
  created_at timestamptz not null default now()
);

create or replace function public.is_platform_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'platform_admin' and active) $$;

create or replace function public.current_agency_id()
returns uuid language sql stable security definer set search_path = public
as $$ select agency_id from public.profiles where id = auth.uid() and active $$;

alter table public.profiles enable row level security;
alter table public.agencies enable row level security;
alter table public.branches enable row level security;
alter table public.wallets enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.bookings enable row level security;

create policy "profile own or platform" on public.profiles for select using (id = auth.uid() or public.is_platform_admin());
create policy "agency isolation" on public.agencies for select using (id = public.current_agency_id() or public.is_platform_admin());
create policy "branch isolation" on public.branches for select using (agency_id = public.current_agency_id() or public.is_platform_admin());
create policy "wallet isolation" on public.wallets for select using (agency_id = public.current_agency_id() or public.is_platform_admin());
create policy "ledger isolation" on public.wallet_transactions for select using (agency_id = public.current_agency_id() or public.is_platform_admin());
create policy "agent own bookings" on public.bookings for select using (created_by = auth.uid() or public.is_platform_admin() or (agency_id = public.current_agency_id() and exists (select 1 from public.profiles where id = auth.uid() and role = 'office_manager')));
create policy "agent creates own booking" on public.bookings for insert with check (created_by = auth.uid() and agency_id = public.current_agency_id());

-- Wallet credit/debit and platform-user management must use server-side Edge Functions.
-- Never expose service_role, Spring API credentials, or balance adjustment endpoints to the browser.


-- SOURCE: supabase/admin-functions.sql
-- Run once in Supabase SQL Editor. This creates an atomic, auditable wallet adjustment.
create or replace function public.platform_adjust_wallet(
  p_agency_id uuid,
  p_amount numeric,
  p_reason text,
  p_created_by uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_amount = 0 then
    raise exception 'Amount must not be zero';
  end if;
  if not exists (select 1 from public.profiles where id = p_created_by and role = 'platform_admin' and active) then
    raise exception 'Only an active platform administrator can adjust a wallet';
  end if;
  update public.wallets
  set balance_cny = balance_cny + p_amount, updated_at = now()
  where agency_id = p_agency_id;
  if not found then
    raise exception 'Wallet not found';
  end if;
  insert into public.wallet_transactions (agency_id, entry_type, amount_cny, reason, created_by)
  values (p_agency_id, 'adjustment', p_amount, p_reason, p_created_by);
end;
$$;


-- SOURCE: supabase/topups.sql
-- Run once in Supabase SQL Editor.
create table if not exists public.topup_requests (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  agency_id uuid not null references public.agencies(id),
  requested_by uuid not null references public.profiles(id),
  amount_cny numeric(14,2) not null check (amount_cny > 0),
  payment_reference text not null,
  note text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by uuid references public.profiles(id)
);

alter table public.topup_requests enable row level security;

drop policy if exists "topup request isolation" on public.topup_requests;
create policy "topup request isolation" on public.topup_requests for select using (
  requested_by = auth.uid()
  or public.is_platform_admin()
  or (
    agency_id = public.current_agency_id()
    and exists (select 1 from public.profiles where id = auth.uid() and role = 'office_manager')
  )
);

-- The platform approval both credits the wallet and saves its ledger entry in one transaction.
create or replace function public.approve_topup_request(p_topup_id uuid, p_approved_by uuid)
returns void language plpgsql security definer set search_path = public as $$
declare request_row public.topup_requests;
begin
  if not exists (select 1 from public.profiles where id = p_approved_by and role = 'platform_admin' and active) then
    raise exception 'Only an active platform administrator can approve top-ups';
  end if;
  select * into request_row from public.topup_requests where id = p_topup_id for update;
  if not found then raise exception 'Top-up request not found'; end if;
  if request_row.status <> 'pending' then raise exception 'This top-up request has already been processed'; end if;
  update public.topup_requests set status = 'approved', approved_at = now(), approved_by = p_approved_by where id = p_topup_id;
  -- An agency wallet may have been reset or may not have been created yet.
  -- Upsert guarantees that an approved invoice always creates its credit.
  insert into public.wallets (agency_id, balance_cny, updated_at)
  values (request_row.agency_id, request_row.amount_cny, now())
  on conflict (agency_id) do update
  set balance_cny = public.wallets.balance_cny + excluded.balance_cny,
      updated_at = now();
  insert into public.wallet_transactions (agency_id, entry_type, amount_cny, reason, created_by)
  values (request_row.agency_id, 'credit', request_row.amount_cny, 'Top-up approved: ' || request_row.invoice_number, p_approved_by);
end;
$$;


-- SOURCE: supabase/mnt-pricing.sql
-- Run once in Supabase SQL Editor. Keeps a permanent pricing snapshot on each invoice/booking.
alter table public.topup_requests
  add column if not exists amount_mnt numeric(14,0),
  add column if not exists service_fee_mnt numeric(14,0) not null default 0,
  add column if not exists total_mnt numeric(14,0),
  add column if not exists official_cny_mnt_rate numeric(14,4),
  add column if not exists markup_mnt numeric(14,2) not null default 4,
  add column if not exists effective_cny_mnt_rate numeric(14,4),
  add column if not exists rate_date date;

alter table public.bookings
  add column if not exists total_mnt numeric(14,0),
  add column if not exists official_cny_mnt_rate numeric(14,4),
  add column if not exists markup_mnt numeric(14,2) not null default 4,
  add column if not exists effective_cny_mnt_rate numeric(14,4),
  add column if not exists rate_date date;


-- SOURCE: supabase/topup-expiry.sql
-- Run once in Supabase SQL Editor. Pending top-up invoices expire at 23:59:59 Ulaanbaatar time.
alter table public.topup_requests
  add column if not exists expires_at timestamptz;

update public.topup_requests
set expires_at = ((date_trunc('day', created_at at time zone 'Asia/Ulaanbaatar') + interval '1 day' - interval '1 second') at time zone 'Asia/Ulaanbaatar')
where expires_at is null;

alter table public.topup_requests
  alter column expires_at set default ((date_trunc('day', now() at time zone 'Asia/Ulaanbaatar') + interval '1 day' - interval '1 second') at time zone 'Asia/Ulaanbaatar');

alter table public.topup_requests
  alter column expires_at set not null;

alter table public.topup_requests drop constraint if exists topup_requests_status_check;
alter table public.topup_requests
  add constraint topup_requests_status_check check (status in ('pending', 'approved', 'rejected', 'cancelled'));

create or replace function public.expire_pending_topup_requests()
returns void language sql security definer set search_path = public as $$
  update public.topup_requests
  set status = 'cancelled'
  where status = 'pending' and expires_at <= now();
$$;

create or replace function public.approve_topup_request(p_topup_id uuid, p_approved_by uuid)
returns void language plpgsql security definer set search_path = public as $$
declare request_row public.topup_requests;
begin
  if not exists (select 1 from public.profiles where id = p_approved_by and role = 'platform_admin' and active) then
    raise exception 'Only an active platform administrator can approve top-ups';
  end if;
  perform public.expire_pending_topup_requests();
  select * into request_row from public.topup_requests where id = p_topup_id for update;
  if not found then raise exception 'Top-up request not found'; end if;
  if request_row.status <> 'pending' then raise exception 'This top-up request has already been processed or has expired'; end if;
  update public.topup_requests set status = 'approved', approved_at = now(), approved_by = p_approved_by where id = p_topup_id;
  update public.wallets set balance_cny = balance_cny + request_row.amount_cny, updated_at = now() where agency_id = request_row.agency_id;
  insert into public.wallet_transactions (agency_id, entry_type, amount_cny, reason, created_by)
  values (request_row.agency_id, 'credit', request_row.amount_cny, 'Top-up approved: ' || request_row.invoice_number, p_approved_by);
end;
$$;


-- SOURCE: supabase/topup-wallet-credit-fix.sql
-- Run once in Supabase SQL Editor.
-- An approved top-up must always create (or increase) the agency wallet.
-- This supersedes earlier versions of approve_topup_request.

create or replace function public.approve_topup_request(p_topup_id uuid, p_approved_by uuid)
returns void language plpgsql security definer set search_path = public as $$
declare request_row public.topup_requests;
begin
  if not exists (
    select 1 from public.profiles
    where id = p_approved_by and role = 'platform_admin' and active
  ) then
    raise exception 'Only an active platform administrator can approve top-ups';
  end if;

  select * into request_row
  from public.topup_requests
  where id = p_topup_id
  for update;

  if not found then
    raise exception 'Top-up request not found';
  end if;
  if request_row.status <> 'pending' then
    raise exception 'This top-up request has already been processed';
  end if;

  update public.topup_requests
  set status = 'approved', approved_at = now(), approved_by = p_approved_by
  where id = p_topup_id;

  insert into public.wallets (agency_id, balance_cny, updated_at)
  values (request_row.agency_id, request_row.amount_cny, now())
  on conflict (agency_id) do update
  set balance_cny = public.wallets.balance_cny + excluded.balance_cny,
      updated_at = now();

  insert into public.wallet_transactions (agency_id, entry_type, amount_cny, reason, created_by)
  values (
    request_row.agency_id,
    'credit',
    request_row.amount_cny,
    'Top-up approved: ' || request_row.invoice_number,
    p_approved_by
  );
end;
$$;


-- SOURCE: supabase/topup-bank-transfer-fees.sql
-- Run once in the Supabase SQL Editor before deploying the bank-fee invoice update.
-- Each invoice snapshots the specific banking charges that were quoted to the agency.
alter table public.topup_requests
  add column if not exists correspondent_fee_cny numeric(14,2) not null default 0,
  add column if not exists correspondent_fee_mnt numeric(14,0) not null default 0,
  add column if not exists khaan_transfer_fee_mnt numeric(14,0) not null default 0,
  add column if not exists bank_transfer_fee_mnt numeric(14,0) not null default 0,
  add column if not exists bank_name text;

comment on column public.topup_requests.correspondent_fee_cny is
  'Golomt Bank CNY OUR fee: 50 CNY through 100,000 CNY, otherwise 150 CNY.';

comment on column public.topup_requests.khaan_transfer_fee_mnt is
  'Historical Khaan Bank transfer-fee snapshot.';

comment on column public.topup_requests.bank_transfer_fee_mnt is
  'Golomt Bank CNY transfer fee: 5000 MNT through 50,000 CNY; 10000 MNT through 100,000 CNY; 20000 MNT above.';


-- SOURCE: supabase/remove-topup-expiry.sql
-- Run once in Supabase SQL Editor to make pending top-up invoices non-expiring.
-- Pending invoices will remain available until a platform administrator approves
-- them, or an authorised user deletes them.

create or replace function public.approve_topup_request(p_topup_id uuid, p_approved_by uuid)
returns void language plpgsql security definer set search_path = public as $$
declare request_row public.topup_requests;
begin
  if not exists (
    select 1 from public.profiles
    where id = p_approved_by and role = 'platform_admin' and active
  ) then
    raise exception 'Only an active platform administrator can approve top-ups';
  end if;

  select * into request_row
  from public.topup_requests
  where id = p_topup_id
  for update;

  if not found then
    raise exception 'Top-up request not found';
  end if;

  if request_row.status <> 'pending' then
    raise exception 'This top-up request has already been processed';
  end if;

  update public.topup_requests
  set status = 'approved', approved_at = now(), approved_by = p_approved_by
  where id = p_topup_id;

  -- Never allow an approved invoice to disappear without crediting a wallet.
  insert into public.wallets (agency_id, balance_cny, updated_at)
  values (request_row.agency_id, request_row.amount_cny, now())
  on conflict (agency_id) do update
  set balance_cny = public.wallets.balance_cny + excluded.balance_cny,
      updated_at = now();

  insert into public.wallet_transactions (agency_id, entry_type, amount_cny, reason, created_by)
  values (
    request_row.agency_id,
    'credit',
    request_row.amount_cny,
    'Top-up approved: ' || request_row.invoice_number,
    p_approved_by
  );
end;
$$;


-- SOURCE: supabase/wallet-funding-controls.sql
-- Run once in Supabase SQL Editor.
-- This reset intentionally preserves bookings and top-up invoices; it clears
-- only wallet balances and the wallet ledger/history requested by the admin.

create or replace function public.platform_reset_all_wallets(p_created_by uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not exists (
    select 1 from public.profiles
    where id = p_created_by and role = 'platform_admin' and active
  ) then
    raise exception 'Only an active platform administrator can reset wallets';
  end if;

  -- Keep an explicit filter here: this is a deliberate ledger reset, not an
  -- unrestricted REST DELETE request.
  delete from public.wallet_transactions where agency_id is not null;
  -- Same safeguard for the balance reset. Every wallet belongs to an agency.
  update public.wallets
  set balance_cny = 0, updated_at = now()
  where agency_id is not null;
end;
$$;

-- Checks funds only. Do not create a ledger debit here: that must happen in
-- the same server-side transaction as a confirmed Spring payment/issue call.
create or replace function public.assert_wallet_funds(
  p_agency_id uuid,
  p_amount_cny numeric,
  p_actor_id uuid
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  current_balance numeric;
begin
  if coalesce(p_amount_cny, 0) < 0 then
    raise exception 'Wallet amount cannot be negative';
  end if;

  if not exists (
    select 1 from public.profiles
    where id = p_actor_id and active
      and (role = 'platform_admin' or agency_id = p_agency_id)
  ) then
    raise exception 'You do not have access to this agency wallet';
  end if;

  select balance_cny into current_balance
  from public.wallets
  where agency_id = p_agency_id
  for share;

  if not found then
    raise exception 'Wallet not found for this agency';
  end if;

  if coalesce(current_balance, 0) < p_amount_cny then
    raise exception 'Insufficient wallet balance. Required: % CNY. Available: % CNY.',
      round(p_amount_cny, 2), round(current_balance, 2);
  end if;

  return jsonb_build_object('ok', true, 'availableCny', current_balance, 'requiredCny', p_amount_cny);
end;
$$;

-- Issue from a prepaid agency wallet. All three operations happen inside one
-- database transaction: validate the user and deadline, debit the wallet,
-- then mark the booking Ticketed. This prevents double-charging and prevents
-- a ticket from being marked issued when the wallet balance is insufficient.
create or replace function public.issue_booking_from_wallet(
  p_booking_id uuid,
  p_actor_id uuid
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  booking_row public.bookings;
  current_balance numeric;
begin
  select * into booking_row
  from public.bookings
  where id = p_booking_id
  for update;

  if not found then
    raise exception 'Booking not found';
  end if;

  if not exists (
    select 1 from public.profiles
    where id = p_actor_id and active
      and (
        role = 'platform_admin'
        or id = booking_row.created_by
        or (role = 'office_manager' and agency_id = booking_row.agency_id)
      )
  ) then
    raise exception 'You do not have access to issue this booking';
  end if;

  if booking_row.status <> 'Reserved' then
    raise exception 'This booking is no longer available for ticket issue';
  end if;

  if booking_row.created_at <= now() - interval '30 minutes' then
    update public.bookings set status = 'Cancelled' where id = booking_row.id;
    raise exception 'The 30-minute ticketing deadline has passed. The reservation has been cancelled.';
  end if;

  select balance_cny into current_balance
  from public.wallets
  where agency_id = booking_row.agency_id
  for update;

  if not found then
    raise exception 'Wallet not found for this agency';
  end if;

  if coalesce(current_balance, 0) < booking_row.total_cny then
    raise exception 'Insufficient wallet balance. Required: % CNY. Available: % CNY.',
      round(booking_row.total_cny, 2), round(current_balance, 2);
  end if;

  update public.wallets
  set balance_cny = balance_cny - booking_row.total_cny,
      updated_at = now()
  where agency_id = booking_row.agency_id;

  insert into public.wallet_transactions (agency_id, entry_type, amount_cny, reason, created_by)
  values (
    booking_row.agency_id,
    'debit',
    -booking_row.total_cny,
    'Ticket issue: ' || coalesce(booking_row.pnr, booking_row.id::text),
    p_actor_id
  );

  update public.bookings
  set status = 'Ticketed'
  where id = booking_row.id;

  return jsonb_build_object(
    'id', booking_row.id,
    'pnr', booking_row.pnr,
    'status', 'Ticketed',
    'debitedCny', booking_row.total_cny,
    'balanceCny', current_balance - booking_row.total_cny
  );
end;
$$;


-- SOURCE: supabase/change-wallet-payment.sql
-- Run before deploying the change-payment update.
create or replace function public.record_change_payment(
  p_pnr text, p_app_id text, p_amount numeric, p_actor uuid,
  p_check_only boolean default false
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  b public.bookings;
  balance numeric;
  previous numeric;
  reference text;
begin
  if p_amount is null or p_amount <= 0 or p_app_id is null or p_app_id !~ '^[0-9]+$' then
    raise exception 'Invalid change payment';
  end if;
  select * into b from public.bookings where pnr = p_pnr;
  if not found then raise exception 'Booking not found'; end if;
  if not exists (select 1 from public.profiles p where p.id = p_actor and p.active
    and (p.role = 'platform_admin' or (p.agency_id = b.agency_id
      and (p.role = 'office_manager' or (p.role = 'agent' and b.created_by = p.id))
      and exists(select 1 from public.agencies a where a.id = b.agency_id and a.active)))) then
    raise exception 'Booking access denied';
  end if;
  select balance_cny into balance from public.wallets where agency_id = b.agency_id for update;
  if not found then raise exception 'Wallet not found'; end if;
  reference := 'Change fee payment: ' || p_pnr || ' | Spring application ' || p_app_id;
  select amount_cny into previous from public.wallet_transactions
    where agency_id = b.agency_id and reason = reference limit 1;
  if found then
    if previous <> -round(p_amount, 2) then raise exception 'Change amount mismatch'; end if;
    return jsonb_build_object('recorded', true);
  end if;
  if p_check_only then
    if balance < round(p_amount, 2) then raise exception 'Insufficient wallet balance'; end if;
    return jsonb_build_object('recorded', false);
  end if;
  -- Supplier has already accepted payment. Always record the actual liability.
  update public.wallets set balance_cny = balance_cny - round(p_amount, 2), updated_at = now()
    where agency_id = b.agency_id;
  insert into public.wallet_transactions(agency_id, entry_type, amount_cny, reason, created_by)
    values(b.agency_id, 'debit', -round(p_amount, 2), reference, p_actor);
  return jsonb_build_object('recorded', true);
end;
$$;
revoke all on function public.record_change_payment(text,text,numeric,uuid,boolean) from public, anon, authenticated;
grant execute on function public.record_change_payment(text,text,numeric,uuid,boolean) to service_role;
notify pgrst, 'reload schema';


-- SOURCE: supabase/agency-contact-details.sql
-- Run once in Supabase SQL Editor before deploying the agency-contact update.
alter table public.agencies
  add column if not exists registration_number text,
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists address text;


-- SOURCE: supabase/agent-contact-details.sql
-- Run before deploying the agent contact and ticket PDF update.

alter table public.profiles
  add column if not exists email text,
  add column if not exists phone text;
update public.profiles p
set email = u.email
from auth.users u
where u.id = p.id and (p.email is null or p.email = '');


-- SOURCE: supabase/security-hardening.sql
-- Apply AFTER existing schema, top-up, wallet-funding-controls and
-- change-wallet-payment migrations, BEFORE deploying the matching backend.
-- No user data is deleted. Never re-run older permission migrations afterwards.

-- Browser callers must not supply an arbitrary actor UUID to SECURITY DEFINER
-- financial functions, or forge booking status/quotes through direct REST writes.
do $$
declare f record;
begin
  for f in select p.oid::regprocedure as signature from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname in (
      'platform_adjust_wallet', 'platform_reset_all_wallets', 'assert_wallet_funds',
      'issue_booking_from_wallet', 'record_change_payment', 'approve_topup_request',
      'expire_pending_topup_requests'
    )
  loop
    execute format('revoke all on function %s from public, anon, authenticated', f.signature);
    execute format('grant execute on function %s to service_role', f.signature);
  end loop;
end $$;

revoke insert, update, delete, truncate, references, trigger on
  public.agencies, public.branches, public.profiles, public.bookings,
  public.wallets, public.wallet_transactions, public.topup_requests
  from public, anon, authenticated;

-- Existing isolation policies remain; this restrictive policy additionally
-- rejects direct reads from disabled users/agencies, even with an unexpired JWT.
create or replace function public.portal_active_reader()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles p where p.id = auth.uid() and p.active
    and (p.role = 'platform_admin' or (p.role in ('agent','office_manager')
      and exists(select 1 from public.agencies a where a.id = p.agency_id and a.active))));
$$;
revoke all on function public.portal_active_reader() from public, anon;
grant execute on function public.portal_active_reader() to authenticated, service_role;
do $$
declare table_name text;
begin
  foreach table_name in array array['agencies','branches','profiles','bookings','wallets','wallet_transactions','topup_requests'] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists "active portal readers only" on public.%I', table_name);
    execute format('create policy "active portal readers only" on public.%I as restrictive for select to authenticated using (public.portal_active_reader())', table_name);
  end loop;
end $$;

-- Approval locks the invoice, changes state, credits wallet and writes ledger
-- inside one transaction. Replaying approval cannot credit the wallet again.
create or replace function public.approve_topup_request(p_topup_id uuid, p_approved_by uuid)
returns void language plpgsql security definer set search_path = public as $$
declare r public.topup_requests;
begin
  if not exists(select 1 from public.profiles where id = p_approved_by and role = 'platform_admin' and active) then
    raise exception 'Only an active platform administrator can approve top-ups'; end if;
  select * into r from public.topup_requests where id = p_topup_id for update;
  if not found then raise exception 'Top-up request not found'; end if;
  if r.status <> 'pending' then raise exception 'This top-up request has already been processed'; end if;
  if r.amount_cny is null or r.amount_cny::text in ('NaN','Infinity','-Infinity') or r.amount_cny <= 0 then
    raise exception 'Invalid top-up credit amount'; end if;
  if not exists(select 1 from public.agencies where id = r.agency_id and active) then raise exception 'Agency is inactive'; end if;
  update public.topup_requests set status = 'approved', approved_at = now(), approved_by = p_approved_by where id = r.id;
  insert into public.wallets(agency_id,balance_cny,updated_at) values(r.agency_id,r.amount_cny,now())
    on conflict(agency_id) do update set balance_cny = public.wallets.balance_cny + excluded.balance_cny, updated_at = now();
  insert into public.wallet_transactions(agency_id,entry_type,amount_cny,reason,created_by)
    values(r.agency_id,'credit',r.amount_cny,'Top-up approved: ' || r.invoice_number,p_approved_by);
end $$;
revoke all on function public.approve_topup_request(uuid,uuid) from public, anon, authenticated;
grant execute on function public.approve_topup_request(uuid,uuid) to service_role;

create table if not exists public.financial_operations (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id),
  booking_id uuid not null references public.bookings(id),
  actor_id uuid not null references public.profiles(id),
  action text not null check (action in ('issue', 'change', 'refund')),
  reference text not null,
  amount_cny numeric(14,2) not null check (amount_cny >= 0),
  state text not null default 'pending' check (state in ('pending', 'needs_review', 'completed', 'released')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists financial_operation_once
  on public.financial_operations(booking_id, action, reference) where state <> 'released';
create unique index if not exists financial_agency_in_flight
  on public.financial_operations(agency_id) where state in ('pending', 'needs_review');
alter table public.financial_operations enable row level security;
revoke all on public.financial_operations from public, anon, authenticated;
grant all on public.financial_operations to service_role;

create or replace function public.begin_financial_operation(
  p_actor uuid, p_pnr text, p_action text, p_reference text, p_amount numeric
) returns uuid language plpgsql security definer set search_path = public as $$
declare b public.bookings; operation_id uuid; current_balance numeric; q jsonb;
begin
  if p_action is null or p_action not in ('issue', 'change', 'refund')
    or p_reference is null or length(p_reference) not between 1 and 500
    or p_amount is null or p_amount::text in ('NaN', 'Infinity', '-Infinity') or p_amount < 0 then
    raise exception 'Invalid financial operation';
  end if;
  select * into b from public.bookings where pnr = p_pnr;
  if not found then raise exception 'Booking not found'; end if;
  if not exists(select 1 from public.profiles p where p.id = p_actor and p.active
    and (p.role = 'platform_admin' or (p.agency_id = b.agency_id
      and (p.role = 'office_manager' or (p.role = 'agent' and b.created_by = p.id))
      and exists(select 1 from public.agencies a where a.id = b.agency_id and a.active)))) then
    raise exception 'Booking access denied';
  end if;
  -- Serialise agency spending across different tickets and backend processes.
  perform pg_advisory_xact_lock(hashtextextended('financial:' || b.agency_id::text, 0));
  select * into b from public.bookings where id = b.id for update;
  if exists(select 1 from public.financial_operations where agency_id = b.agency_id
    and state in ('pending','needs_review')) then
    raise exception 'Agency has a financial operation in progress or awaiting reconciliation. Do not retry payment';
  end if;
  if exists(select 1 from public.financial_operations where booking_id = b.id
    and action = p_action and reference = p_reference and state <> 'released') then
    raise exception 'This financial operation has already been submitted';
  end if;
  if p_action = 'issue' then
    if b.status <> 'Reserved' or b.created_at <= now() - interval '30 minutes'
      or p_amount <= 0 or round(p_amount,2) <> b.total_cny then
      raise exception 'Booking is not eligible for ticket issue';
    end if;
  else
    if b.status <> 'Ticketed' then raise exception 'Ticketed booking required'; end if;
  end if;
  if p_action = 'change' then
    q := b.itinerary->'changeQuotes'->p_reference;
    if q is null or (q->>'securityVersion') is distinct from '1'
      or (q->>'appId') is distinct from p_reference
      or not (q ? 'quotedAt') or not ((q->'amountsCny') ? 'additionalPayment')
      or (q->>'quotedAt')::timestamptz < now() - interval '15 minutes'
      or (q->>'quotedAt')::timestamptz > now()
      or round((q->'amountsCny'->>'additionalPayment')::numeric,2) is distinct from round(p_amount,2) then
      raise exception 'A current matching server quote is required';
    end if;
  end if;
  select balance_cny into current_balance from public.wallets where agency_id = b.agency_id for update;
  if not found then raise exception 'Wallet not found'; end if;
  if p_action <> 'refund' and (current_balance::text in ('NaN','Infinity','-Infinity') or current_balance < round(p_amount,2)) then raise exception 'Insufficient wallet balance'; end if;
  insert into public.financial_operations(agency_id, booking_id, actor_id, action, reference, amount_cny)
    values(b.agency_id, b.id, p_actor, p_action, p_reference, round(p_amount,2)) returning id into operation_id;
  return operation_id;
end $$;

create or replace function public.finish_financial_operation(p_id uuid, p_actor uuid, p_state text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if p_state is null or p_state not in ('completed','needs_review') then raise exception 'Invalid operation state'; end if;
  update public.financial_operations set state = p_state, updated_at = now()
    where id = p_id and actor_id = p_actor and state = 'pending';
  if not found then raise exception 'Financial operation cannot be updated'; end if;
end $$;
revoke all on function public.begin_financial_operation(uuid,text,text,text,numeric) from public, anon, authenticated;
revoke all on function public.finish_financial_operation(uuid,uuid,text) from public, anon, authenticated;
grant execute on function public.begin_financial_operation(uuid,text,text,text,numeric) to service_role;
grant execute on function public.finish_financial_operation(uuid,uuid,text) to service_role;

-- Prevent manual balance changes racing with a supplier payment.
create or replace function public.platform_adjust_wallet(p_agency_id uuid, p_amount numeric, p_reason text, p_created_by uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if p_amount is null or p_amount::text in ('NaN','Infinity','-Infinity') or round(p_amount,2) = 0
    or p_reason is null or length(trim(p_reason)) not between 1 and 1000 then raise exception 'Invalid wallet adjustment'; end if;
  if not exists(select 1 from public.profiles where id = p_created_by and role = 'platform_admin' and active) then
    raise exception 'Only an active platform administrator can adjust a wallet'; end if;
  perform pg_advisory_xact_lock(hashtextextended('financial:' || p_agency_id::text, 0));
  if exists(select 1 from public.financial_operations where agency_id = p_agency_id and state in ('pending','needs_review')) then
    raise exception 'Resolve the pending financial operation before adjusting this wallet'; end if;
  update public.wallets set balance_cny = balance_cny + round(p_amount,2), updated_at = now() where agency_id = p_agency_id;
  if not found then raise exception 'Wallet not found'; end if;
  insert into public.wallet_transactions(agency_id,entry_type,amount_cny,reason,created_by)
    values(p_agency_id,'adjustment',round(p_amount,2),p_reason,p_created_by);
end $$;
revoke all on function public.platform_adjust_wallet(uuid,numeric,text,uuid) from public, anon, authenticated;
grant execute on function public.platform_adjust_wallet(uuid,numeric,text,uuid) to service_role;

notify pgrst, 'reload schema';

commit;
