-- TEST PROJECT ONLY. Generated by deploy/staging/build-schema.mjs.
-- Refuses databases with existing public tables or authentication users.
-- No production business data, credentials or users are included.
begin;
do $$
begin
  if exists (select 1 from pg_tables where schemaname = 'public')
     or exists (select 1 from auth.users) then
    raise exception 'STOP: this installer requires an EMPTY TEST Supabase project.';
  end if;
end $$;

-- SOURCE: supabase/schema.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run in Supabase SQL Editor after creating the project.
create type public.user_role as enum ('agent', 'office_manager', 'platform_admin');
create type public.wallet_entry_type as enum ('credit', 'debit', 'adjustment');

create table public.agencies (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  registration_number text,
  email text,
  phone text,
  address text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.branches (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (agency_id, name)
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  agency_id uuid references public.agencies(id),
  branch_id uuid references public.branches(id),
  role public.user_role not null default 'agent',
  full_name text not null,
  email text,
  phone text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check ((role = 'platform_admin') or agency_id is not null)
);

create table public.wallets (
  agency_id uuid primary key references public.agencies(id) on delete cascade,
  balance_cny numeric(14,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table public.wallet_transactions (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id),
  entry_type public.wallet_entry_type not null,
  amount_cny numeric(14,2) not null check (amount_cny <> 0),
  booking_id uuid,
  reason text not null,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  pnr text unique,
  agency_id uuid not null references public.agencies(id),
  branch_id uuid references public.branches(id),
  created_by uuid not null references public.profiles(id),
  status text not null default 'draft',
  total_cny numeric(14,2) not null check (total_cny >= 0),
  itinerary jsonb not null,
  passengers jsonb not null,
  created_at timestamptz not null default now()
);

create or replace function public.is_platform_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'platform_admin' and active) $$;

create or replace function public.current_agency_id()
returns uuid language sql stable security definer set search_path = public
as $$ select agency_id from public.profiles where id = auth.uid() and active $$;

alter table public.profiles enable row level security;
alter table public.agencies enable row level security;
alter table public.branches enable row level security;
alter table public.wallets enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.bookings enable row level security;

create policy "profile own or platform" on public.profiles for select using (id = auth.uid() or public.is_platform_admin());
create policy "agency isolation" on public.agencies for select using (id = public.current_agency_id() or public.is_platform_admin());
create policy "branch isolation" on public.branches for select using (agency_id = public.current_agency_id() or public.is_platform_admin());
create policy "wallet isolation" on public.wallets for select using (agency_id = public.current_agency_id() or public.is_platform_admin());
create policy "ledger isolation" on public.wallet_transactions for select using (agency_id = public.current_agency_id() or public.is_platform_admin());
create policy "agent own bookings" on public.bookings for select using (created_by = auth.uid() or public.is_platform_admin() or (agency_id = public.current_agency_id() and exists (select 1 from public.profiles where id = auth.uid() and role = 'office_manager')));
create policy "agent creates own booking" on public.bookings for insert with check (created_by = auth.uid() and agency_id = public.current_agency_id());

-- Wallet credit/debit and platform-user management must use server-side Edge Functions.
-- Never expose service_role, Spring API credentials, or balance adjustment endpoints to the browser.


-- SOURCE: supabase/admin-functions.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run once in Supabase SQL Editor. This creates an atomic, auditable wallet adjustment.
create or replace function public.platform_adjust_wallet(
  p_agency_id uuid,
  p_amount numeric,
  p_reason text,
  p_created_by uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_amount = 0 then
    raise exception 'Amount must not be zero';
  end if;
  if not exists (select 1 from public.profiles where id = p_created_by and role = 'platform_admin' and active) then
    raise exception 'Only an active platform administrator can adjust a wallet';
  end if;
  update public.wallets
  set balance_cny = balance_cny + p_amount, updated_at = now()
  where agency_id = p_agency_id;
  if not found then
    raise exception 'Wallet not found';
  end if;
  insert into public.wallet_transactions (agency_id, entry_type, amount_cny, reason, created_by)
  values (p_agency_id, 'adjustment', p_amount, p_reason, p_created_by);
end;
$$;


-- SOURCE: supabase/topups.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run once in Supabase SQL Editor.
create table if not exists public.topup_requests (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  agency_id uuid not null references public.agencies(id),
  requested_by uuid not null references public.profiles(id),
  amount_cny numeric(14,2) not null check (amount_cny > 0),
  payment_reference text not null,
  note text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by uuid references public.profiles(id)
);

alter table public.topup_requests enable row level security;

drop policy if exists "topup request isolation" on public.topup_requests;
create policy "topup request isolation" on public.topup_requests for select using (
  requested_by = auth.uid()
  or public.is_platform_admin()
  or (
    agency_id = public.current_agency_id()
    and exists (select 1 from public.profiles where id = auth.uid() and role = 'office_manager')
  )
);

-- The platform approval both credits the wallet and saves its ledger entry in one transaction.
create or replace function public.approve_topup_request(p_topup_id uuid, p_approved_by uuid)
returns void language plpgsql security definer set search_path = public as $$
declare request_row public.topup_requests;
begin
  if not exists (select 1 from public.profiles where id = p_approved_by and role = 'platform_admin' and active) then
    raise exception 'Only an active platform administrator can approve top-ups';
  end if;
  select * into request_row from public.topup_requests where id = p_topup_id for update;
  if not found then raise exception 'Top-up request not found'; end if;
  if request_row.status <> 'pending' then raise exception 'This top-up request has already been processed'; end if;
  update public.topup_requests set status = 'approved', approved_at = now(), approved_by = p_approved_by where id = p_topup_id;
  -- An agency wallet may have been reset or may not have been created yet.
  -- Upsert guarantees that an approved invoice always creates its credit.
  insert into public.wallets (agency_id, balance_cny, updated_at)
  values (request_row.agency_id, request_row.amount_cny, now())
  on conflict (agency_id) do update
  set balance_cny = public.wallets.balance_cny + excluded.balance_cny,
      updated_at = now();
  insert into public.wallet_transactions (agency_id, entry_type, amount_cny, reason, created_by)
  values (request_row.agency_id, 'credit', request_row.amount_cny, 'Top-up approved: ' || request_row.invoice_number, p_approved_by);
end;
$$;


-- SOURCE: supabase/mnt-pricing.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run once in Supabase SQL Editor. Keeps a permanent pricing snapshot on each invoice/booking.
alter table public.topup_requests
  add column if not exists amount_mnt numeric(14,0),
  add column if not exists service_fee_mnt numeric(14,0) not null default 0,
  add column if not exists total_mnt numeric(14,0),
  add column if not exists official_cny_mnt_rate numeric(14,4),
  add column if not exists markup_mnt numeric(14,2) not null default 4,
  add column if not exists effective_cny_mnt_rate numeric(14,4),
  add column if not exists rate_date date;

alter table public.bookings
  add column if not exists total_mnt numeric(14,0),
  add column if not exists official_cny_mnt_rate numeric(14,4),
  add column if not exists markup_mnt numeric(14,2) not null default 4,
  add column if not exists effective_cny_mnt_rate numeric(14,4),
  add column if not exists rate_date date;


-- SOURCE: supabase/topup-expiry.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- HISTORICAL EMPTY-PROJECT BOOTSTRAP ONLY. See supabase/migrations.
alter table public.topup_requests add column if not exists expires_at timestamptz;
alter table public.topup_requests alter column expires_at drop default;
alter table public.topup_requests alter column expires_at drop not null;
alter table public.topup_requests drop constraint if exists topup_requests_status_check;
alter table public.topup_requests add constraint topup_requests_status_check
  check (status in ('pending', 'approved', 'rejected', 'cancelled'));

create or replace function public.expire_pending_topup_requests()
returns void language plpgsql security invoker set search_path = '' as $$
begin
  raise exception using errcode = '42501', message = 'INVOICE_EXPIRY_DISABLED';
end;
$$;
revoke all on function public.expire_pending_topup_requests()
  from public, anon, authenticated, service_role;


-- SOURCE: supabase/topup-wallet-credit-fix.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run once in Supabase SQL Editor.
-- An approved top-up must always create (or increase) the agency wallet.
-- This supersedes earlier versions of approve_topup_request.

create or replace function public.approve_topup_request(p_topup_id uuid, p_approved_by uuid)
returns void language plpgsql security definer set search_path = public as $$
declare request_row public.topup_requests;
begin
  if not exists (
    select 1 from public.profiles
    where id = p_approved_by and role = 'platform_admin' and active
  ) then
    raise exception 'Only an active platform administrator can approve top-ups';
  end if;

  select * into request_row
  from public.topup_requests
  where id = p_topup_id
  for update;

  if not found then
    raise exception 'Top-up request not found';
  end if;
  if request_row.status <> 'pending' then
    raise exception 'This top-up request has already been processed';
  end if;

  update public.topup_requests
  set status = 'approved', approved_at = now(), approved_by = p_approved_by
  where id = p_topup_id;

  insert into public.wallets (agency_id, balance_cny, updated_at)
  values (request_row.agency_id, request_row.amount_cny, now())
  on conflict (agency_id) do update
  set balance_cny = public.wallets.balance_cny + excluded.balance_cny,
      updated_at = now();

  insert into public.wallet_transactions (agency_id, entry_type, amount_cny, reason, created_by)
  values (
    request_row.agency_id,
    'credit',
    request_row.amount_cny,
    'Top-up approved: ' || request_row.invoice_number,
    p_approved_by
  );
end;
$$;


-- SOURCE: supabase/topup-bank-transfer-fees.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run once in the Supabase SQL Editor before deploying the bank-fee invoice update.
-- Each invoice snapshots the specific banking charges that were quoted to the agency.
alter table public.topup_requests
  add column if not exists correspondent_fee_cny numeric(14,2) not null default 0,
  add column if not exists correspondent_fee_mnt numeric(14,0) not null default 0,
  add column if not exists khaan_transfer_fee_mnt numeric(14,0) not null default 0,
  add column if not exists bank_transfer_fee_mnt numeric(14,0) not null default 0,
  add column if not exists bank_name text;

comment on column public.topup_requests.correspondent_fee_cny is
  'Golomt Bank CNY OUR fee: 50 CNY through 100,000 CNY, otherwise 150 CNY.';

comment on column public.topup_requests.khaan_transfer_fee_mnt is
  'Historical Khaan Bank transfer-fee snapshot.';

comment on column public.topup_requests.bank_transfer_fee_mnt is
  'Golomt Bank CNY transfer fee: 5000 MNT through 50,000 CNY; 10000 MNT through 100,000 CNY; 20000 MNT above.';


-- SOURCE: supabase/remove-topup-expiry.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Pending invoices never expire. Does not replace any approval function.
alter table public.topup_requests alter column expires_at drop default;
alter table public.topup_requests alter column expires_at drop not null;


-- SOURCE: supabase/wallet-funding-controls.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run once in Supabase SQL Editor.
-- Wallet reset is retired. Keep a non-mutating stub for old callers;
-- never zero balances or delete financial history through this function.

create or replace function public.platform_reset_all_wallets(p_created_by uuid)
returns void language plpgsql security invoker set search_path = '' as $$
begin
  raise exception using errcode = '42501', message = 'WALLET_RESET_DISABLED';
end;
$$;
revoke all on function public.platform_reset_all_wallets(uuid)
  from public, anon, authenticated, service_role;
comment on function public.platform_reset_all_wallets(uuid) is
  'Retired: wallet balances and financial history must never be reset.';

-- Checks funds only. Do not create a ledger debit here: that must happen in
-- the same server-side transaction as a confirmed Spring payment/issue call.
create or replace function public.assert_wallet_funds(
  p_agency_id uuid,
  p_amount_cny numeric,
  p_actor_id uuid
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  current_balance numeric;
begin
  if coalesce(p_amount_cny, 0) < 0 then
    raise exception 'Wallet amount cannot be negative';
  end if;

  if not exists (
    select 1 from public.profiles
    where id = p_actor_id and active
      and (role = 'platform_admin' or agency_id = p_agency_id)
  ) then
    raise exception 'You do not have access to this agency wallet';
  end if;

  select balance_cny into current_balance
  from public.wallets
  where agency_id = p_agency_id
  for share;

  if not found then
    raise exception 'Wallet not found for this agency';
  end if;

  if coalesce(current_balance, 0) < p_amount_cny then
    raise exception 'Insufficient wallet balance. Required: % CNY. Available: % CNY.',
      round(p_amount_cny, 2), round(current_balance, 2);
  end if;

  return jsonb_build_object('ok', true, 'availableCny', current_balance, 'requiredCny', p_amount_cny);
end;
$$;

-- Issue from a prepaid agency wallet. All three operations happen inside one
-- database transaction: validate the user and deadline, debit the wallet,
-- then mark the booking Ticketed. This prevents double-charging and prevents
-- a ticket from being marked issued when the wallet balance is insufficient.
create or replace function public.issue_booking_from_wallet(
  p_booking_id uuid,
  p_actor_id uuid
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  booking_row public.bookings;
  current_balance numeric;
begin
  select * into booking_row
  from public.bookings
  where id = p_booking_id
  for update;

  if not found then
    raise exception 'Booking not found';
  end if;

  if not exists (
    select 1 from public.profiles
    where id = p_actor_id and active
      and (
        role = 'platform_admin'
        or id = booking_row.created_by
        or (role = 'office_manager' and agency_id = booking_row.agency_id)
      )
  ) then
    raise exception 'You do not have access to issue this booking';
  end if;

  if booking_row.status <> 'Reserved' then
    raise exception 'This booking is no longer available for ticket issue';
  end if;

  if booking_row.created_at <= now() - interval '30 minutes' then
    update public.bookings set status = 'Cancelled' where id = booking_row.id;
    raise exception 'The 30-minute ticketing deadline has passed. The reservation has been cancelled.';
  end if;

  select balance_cny into current_balance
  from public.wallets
  where agency_id = booking_row.agency_id
  for update;

  if not found then
    raise exception 'Wallet not found for this agency';
  end if;

  if coalesce(current_balance, 0) < booking_row.total_cny then
    raise exception 'Insufficient wallet balance. Required: % CNY. Available: % CNY.',
      round(booking_row.total_cny, 2), round(current_balance, 2);
  end if;

  update public.wallets
  set balance_cny = balance_cny - booking_row.total_cny,
      updated_at = now()
  where agency_id = booking_row.agency_id;

  insert into public.wallet_transactions (agency_id, entry_type, amount_cny, reason, created_by)
  values (
    booking_row.agency_id,
    'debit',
    -booking_row.total_cny,
    'Ticket issue: ' || coalesce(booking_row.pnr, booking_row.id::text),
    p_actor_id
  );

  update public.bookings
  set status = 'Ticketed'
  where id = booking_row.id;

  return jsonb_build_object(
    'id', booking_row.id,
    'pnr', booking_row.pnr,
    'status', 'Ticketed',
    'debitedCny', booking_row.total_cny,
    'balanceCny', current_balance - booking_row.total_cny
  );
end;
$$;


-- SOURCE: supabase/change-wallet-payment.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run before deploying the change-payment update.
create or replace function public.record_change_payment(
  p_pnr text, p_app_id text, p_amount numeric, p_actor uuid,
  p_check_only boolean default false
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  b public.bookings;
  balance numeric;
  previous numeric;
  reference text;
begin
  if p_amount is null or p_amount <= 0 or p_app_id is null or p_app_id !~ '^[0-9]+$' then
    raise exception 'Invalid change payment';
  end if;
  select * into b from public.bookings where pnr = p_pnr;
  if not found then raise exception 'Booking not found'; end if;
  if not exists (select 1 from public.profiles p where p.id = p_actor and p.active
    and (p.role = 'platform_admin' or (p.agency_id = b.agency_id
      and (p.role = 'office_manager' or (p.role = 'agent' and b.created_by = p.id))
      and exists(select 1 from public.agencies a where a.id = b.agency_id and a.active)))) then
    raise exception 'Booking access denied';
  end if;
  select balance_cny into balance from public.wallets where agency_id = b.agency_id for update;
  if not found then raise exception 'Wallet not found'; end if;
  reference := 'Change fee payment: ' || p_pnr || ' | Spring application ' || p_app_id;
  select amount_cny into previous from public.wallet_transactions
    where agency_id = b.agency_id and reason = reference limit 1;
  if found then
    if previous <> -round(p_amount, 2) then raise exception 'Change amount mismatch'; end if;
    return jsonb_build_object('recorded', true);
  end if;
  if p_check_only then
    if balance < round(p_amount, 2) then raise exception 'Insufficient wallet balance'; end if;
    return jsonb_build_object('recorded', false);
  end if;
  -- Supplier has already accepted payment. Always record the actual liability.
  update public.wallets set balance_cny = balance_cny - round(p_amount, 2), updated_at = now()
    where agency_id = b.agency_id;
  insert into public.wallet_transactions(agency_id, entry_type, amount_cny, reason, created_by)
    values(b.agency_id, 'debit', -round(p_amount, 2), reference, p_actor);
  return jsonb_build_object('recorded', true);
end;
$$;
revoke all on function public.record_change_payment(text,text,numeric,uuid,boolean) from public, anon, authenticated;
grant execute on function public.record_change_payment(text,text,numeric,uuid,boolean) to service_role;
notify pgrst, 'reload schema';


-- SOURCE: supabase/agency-contact-details.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run once in Supabase SQL Editor before deploying the agency-contact update.
alter table public.agencies
  add column if not exists registration_number text,
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists address text;


-- SOURCE: supabase/agent-contact-details.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run before deploying the agent contact and ticket PDF update.
alter table public.profiles
  add column if not exists email text,
  add column if not exists phone text;
update public.profiles p
set email = u.email
from auth.users u
where u.id = p.id and (p.email is null or p.email = '');


-- SOURCE: supabase/spring-status-sync.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run once on the target Supabase project before deploying the worker.
-- No booking/payment/itinerary values are rewritten.
alter table public.bookings add column if not exists supplier_status jsonb not null default '{}'::jsonb;
alter table public.bookings add column if not exists supplier_status_next_check_at timestamptz default now();
alter table public.bookings add column if not exists supplier_status_lease_until timestamptz;
alter table public.bookings add column if not exists supplier_status_lease_id uuid;
create index if not exists bookings_supplier_status_due_idx
  on public.bookings(supplier_status_next_check_at) where status = 'Ticketed';

create or replace function public.claim_spring_status_checks()
returns setof public.bookings language plpgsql security definer set search_path = public
as $$
begin
  return query
  with candidates as (
    select b.id from public.bookings b
    where b.status = 'Ticketed' and b.pnr not like 'B2B%'
      and (b.supplier_status_lease_until is null or b.supplier_status_lease_until < now())
      and (b.supplier_status_next_check_at <= now()
        or b.supplier_status->>'revision' is distinct from md5(jsonb_build_array(b.itinerary->'flights', b.itinerary->'departureDate', b.itinerary->'returnDate', b.passengers)::text))
    order by b.supplier_status_next_check_at nulls first, b.id
    limit 5 for update skip locked
  )
  update public.bookings b set supplier_status_lease_until = now() + interval '5 minutes',
    supplier_status_lease_id = gen_random_uuid(),
    supplier_status = b.supplier_status || jsonb_build_object('claimedRevision', md5(jsonb_build_array(b.itinerary->'flights', b.itinerary->'departureDate', b.itinerary->'returnDate', b.passengers)::text))
  from candidates c where b.id = c.id returning b.*;
end;
$$;

create or replace function public.finish_spring_status_check(p_booking_id uuid, p_lease_id uuid, p_revision text, p_result jsonb)
returns boolean language plpgsql security definer set search_path = public
as $$
declare b public.bookings; current_revision text;
begin
  select * into b from public.bookings where id = p_booking_id for update;
  if not found or b.supplier_status_lease_id is distinct from p_lease_id or p_lease_id is null then return false; end if;
  current_revision := md5(jsonb_build_array(b.itinerary->'flights', b.itinerary->'departureDate', b.itinerary->'returnDate', b.passengers)::text);
  if b.status <> 'Ticketed' or current_revision is distinct from p_revision then
    update public.bookings set supplier_status_lease_until = null, supplier_status_lease_id = null,
      supplier_status_next_check_at = now() where id = b.id;
    return false;
  end if;
  update public.bookings set
    supplier_status = case when p_result is null then
      b.supplier_status || jsonb_build_object('result', 'error', 'lastAttemptAt', now(), 'revision', current_revision)
    else p_result || jsonb_build_object('revision', current_revision) end,
    supplier_status_next_check_at = now() + case
      when p_result->>'result' = 'ok' and jsonb_array_length(p_result->'records') > 0
        and not exists (select 1 from jsonb_array_elements(p_result->'records') r where r->>'flag' <> '40')
      then interval '24 hours' else interval '15 minutes' end,
    supplier_status_lease_until = null, supplier_status_lease_id = null
  where id = b.id;
  return true;
end;
$$;
revoke all on function public.claim_spring_status_checks() from public, anon, authenticated;
revoke all on function public.finish_spring_status_check(uuid, uuid, text, jsonb) from public, anon, authenticated;
grant execute on function public.claim_spring_status_checks() to service_role;
grant execute on function public.finish_spring_status_check(uuid, uuid, text, jsonb) to service_role;
notify pgrst, 'reload schema';


-- SOURCE: supabase/security-hardening.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Apply AFTER existing schema, top-up, wallet-funding-controls and
-- change-wallet-payment migrations, BEFORE deploying the matching backend.
-- No user data is deleted. Never re-run older permission migrations afterwards.

-- Browser callers must not supply an arbitrary actor UUID to SECURITY DEFINER
-- financial functions, or forge booking status/quotes through direct REST writes.
do $$
declare f record;
begin
  for f in select p.oid::regprocedure as signature from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname in (
      'platform_adjust_wallet', 'assert_wallet_funds',
      'issue_booking_from_wallet', 'record_change_payment', 'approve_topup_request'
    )
  loop
    execute format('revoke all on function %s from public, anon, authenticated', f.signature);
    execute format('grant execute on function %s to service_role', f.signature);
  end loop;
end $$;

-- A retired reset must not regain execution privileges during bootstrap.
revoke all on function public.platform_reset_all_wallets(uuid)
  from public, anon, authenticated, service_role;
revoke all on function public.expire_pending_topup_requests()
  from public, anon, authenticated, service_role;

revoke insert, update, delete, truncate, references, trigger on
  public.agencies, public.branches, public.profiles, public.bookings,
  public.wallets, public.wallet_transactions, public.topup_requests
  from public, anon, authenticated;

-- Existing isolation policies remain; this restrictive policy additionally
-- rejects direct reads from disabled users/agencies, even with an unexpired JWT.
create or replace function public.portal_active_reader()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles p where p.id = auth.uid() and p.active
    and (p.role = 'platform_admin' or (p.role in ('agent','office_manager')
      and exists(select 1 from public.agencies a where a.id = p.agency_id and a.active))));
$$;
revoke all on function public.portal_active_reader() from public, anon;
grant execute on function public.portal_active_reader() to authenticated, service_role;
do $$
declare table_name text;
begin
  foreach table_name in array array['agencies','branches','profiles','bookings','wallets','wallet_transactions','topup_requests'] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists "active portal readers only" on public.%I', table_name);
    execute format('create policy "active portal readers only" on public.%I as restrictive for select to authenticated using (public.portal_active_reader())', table_name);
  end loop;
end $$;

-- Approval locks the invoice, changes state, credits wallet and writes ledger
-- inside one transaction. Replaying approval cannot credit the wallet again.
create or replace function public.approve_topup_request(p_topup_id uuid, p_approved_by uuid)
returns void language plpgsql security definer set search_path = public as $$
declare r public.topup_requests;
begin
  if not exists(select 1 from public.profiles where id = p_approved_by and role = 'platform_admin' and active) then
    raise exception 'Only an active platform administrator can approve top-ups'; end if;
  select * into r from public.topup_requests where id = p_topup_id for update;
  if not found then raise exception 'Top-up request not found'; end if;
  if r.status <> 'pending' then raise exception 'This top-up request has already been processed'; end if;
  if r.amount_cny is null or r.amount_cny::text in ('NaN','Infinity','-Infinity') or r.amount_cny <= 0 then
    raise exception 'Invalid top-up credit amount'; end if;
  if not exists(select 1 from public.agencies where id = r.agency_id and active) then raise exception 'Agency is inactive'; end if;
  update public.topup_requests set status = 'approved', approved_at = now(), approved_by = p_approved_by where id = r.id;
  insert into public.wallets(agency_id,balance_cny,updated_at) values(r.agency_id,r.amount_cny,now())
    on conflict(agency_id) do update set balance_cny = public.wallets.balance_cny + excluded.balance_cny, updated_at = now();
  insert into public.wallet_transactions(agency_id,entry_type,amount_cny,reason,created_by)
    values(r.agency_id,'credit',r.amount_cny,'Top-up approved: ' || r.invoice_number,p_approved_by);
end $$;
revoke all on function public.approve_topup_request(uuid,uuid) from public, anon, authenticated;
grant execute on function public.approve_topup_request(uuid,uuid) to service_role;

create table if not exists public.financial_operations (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id),
  booking_id uuid not null references public.bookings(id),
  actor_id uuid not null references public.profiles(id),
  action text not null check (action in ('issue', 'change', 'refund')),
  reference text not null,
  amount_cny numeric(14,2) not null check (amount_cny >= 0),
  state text not null default 'pending' check (state in ('pending', 'needs_review', 'completed', 'released')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists financial_operation_once
  on public.financial_operations(booking_id, action, reference) where state <> 'released';
create unique index if not exists financial_agency_in_flight
  on public.financial_operations(agency_id) where state in ('pending', 'needs_review');
alter table public.financial_operations enable row level security;
revoke all on public.financial_operations from public, anon, authenticated;
grant all on public.financial_operations to service_role;

create or replace function public.begin_financial_operation(
  p_actor uuid, p_pnr text, p_action text, p_reference text, p_amount numeric
) returns uuid language plpgsql security definer set search_path = public as $$
declare b public.bookings; operation_id uuid; current_balance numeric; q jsonb;
begin
  if p_action is null or p_action not in ('issue', 'change', 'refund')
    or p_reference is null or length(p_reference) not between 1 and 500
    or p_amount is null or p_amount::text in ('NaN', 'Infinity', '-Infinity') or p_amount < 0 then
    raise exception 'Invalid financial operation';
  end if;
  select * into b from public.bookings where pnr = p_pnr;
  if not found then raise exception 'Booking not found'; end if;
  if not exists(select 1 from public.profiles p where p.id = p_actor and p.active
    and (p.role = 'platform_admin' or (p.agency_id = b.agency_id
      and (p.role = 'office_manager' or (p.role = 'agent' and b.created_by = p.id))
      and exists(select 1 from public.agencies a where a.id = b.agency_id and a.active)))) then
    raise exception 'Booking access denied';
  end if;
  -- Serialise agency spending across different tickets and backend processes.
  perform pg_advisory_xact_lock(hashtextextended('financial:' || b.agency_id::text, 0));
  select * into b from public.bookings where id = b.id for update;
  if exists(select 1 from public.financial_operations where agency_id = b.agency_id
    and state in ('pending','needs_review')) then
    raise exception 'Agency has a financial operation in progress or awaiting reconciliation. Do not retry payment';
  end if;
  if exists(select 1 from public.financial_operations where booking_id = b.id
    and action = p_action and reference = p_reference and state <> 'released') then
    raise exception 'This financial operation has already been submitted';
  end if;
  if p_action = 'issue' then
    if b.status <> 'Reserved' or b.created_at <= now() - interval '30 minutes'
      or p_amount <= 0 or round(p_amount,2) <> b.total_cny then
      raise exception 'Booking is not eligible for ticket issue';
    end if;
  else
    if b.status <> 'Ticketed' then raise exception 'Ticketed booking required'; end if;
  end if;
  if p_action = 'change' then
    q := b.itinerary->'changeQuotes'->p_reference;
    if q is null or (q->>'securityVersion') is distinct from '1'
      or (q->>'appId') is distinct from p_reference
      or not (q ? 'quotedAt') or not ((q->'amountsCny') ? 'additionalPayment')
      or (q->>'quotedAt')::timestamptz < now() - interval '15 minutes'
      or (q->>'quotedAt')::timestamptz > now()
      or round((q->'amountsCny'->>'additionalPayment')::numeric,2) is distinct from round(p_amount,2) then
      raise exception 'A current matching server quote is required';
    end if;
  end if;
  select balance_cny into current_balance from public.wallets where agency_id = b.agency_id for update;
  if not found then raise exception 'Wallet not found'; end if;
  if p_action <> 'refund' and (current_balance::text in ('NaN','Infinity','-Infinity') or current_balance < round(p_amount,2)) then raise exception 'Insufficient wallet balance'; end if;
  insert into public.financial_operations(agency_id, booking_id, actor_id, action, reference, amount_cny)
    values(b.agency_id, b.id, p_actor, p_action, p_reference, round(p_amount,2)) returning id into operation_id;
  return operation_id;
end $$;

create or replace function public.finish_financial_operation(p_id uuid, p_actor uuid, p_state text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if p_state is null or p_state not in ('completed','needs_review') then raise exception 'Invalid operation state'; end if;
  update public.financial_operations set state = p_state, updated_at = now()
    where id = p_id and actor_id = p_actor and state = 'pending';
  if not found then raise exception 'Financial operation cannot be updated'; end if;
end $$;
revoke all on function public.begin_financial_operation(uuid,text,text,text,numeric) from public, anon, authenticated;
revoke all on function public.finish_financial_operation(uuid,uuid,text) from public, anon, authenticated;
grant execute on function public.begin_financial_operation(uuid,text,text,text,numeric) to service_role;
grant execute on function public.finish_financial_operation(uuid,uuid,text) to service_role;

-- Prevent manual balance changes racing with a supplier payment.
create or replace function public.platform_adjust_wallet(p_agency_id uuid, p_amount numeric, p_reason text, p_created_by uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if p_amount is null or p_amount::text in ('NaN','Infinity','-Infinity') or round(p_amount,2) = 0
    or p_reason is null or length(trim(p_reason)) not between 1 and 1000 then raise exception 'Invalid wallet adjustment'; end if;
  if not exists(select 1 from public.profiles where id = p_created_by and role = 'platform_admin' and active) then
    raise exception 'Only an active platform administrator can adjust a wallet'; end if;
  perform pg_advisory_xact_lock(hashtextextended('financial:' || p_agency_id::text, 0));
  if exists(select 1 from public.financial_operations where agency_id = p_agency_id and state in ('pending','needs_review')) then
    raise exception 'Resolve the pending financial operation before adjusting this wallet'; end if;
  update public.wallets set balance_cny = balance_cny + round(p_amount,2), updated_at = now() where agency_id = p_agency_id;
  if not found then raise exception 'Wallet not found'; end if;
  insert into public.wallet_transactions(agency_id,entry_type,amount_cny,reason,created_by)
    values(p_agency_id,'adjustment',round(p_amount,2),p_reason,p_created_by);
end $$;
revoke all on function public.platform_adjust_wallet(uuid,numeric,text,uuid) from public, anon, authenticated;
grant execute on function public.platform_adjust_wallet(uuid,numeric,text,uuid) to service_role;

notify pgrst, 'reload schema';


-- SOURCE: supabase/retail-rounding.sql
-- HISTORICAL BOOTSTRAP ONLY: current releases use supabase/migrations.
do $historical_guard$
declare registered boolean := false;
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    execute 'select exists(select 1 from supabase_migrations.schema_migrations where name = ''nexahub_baseline'')' into registered;
  end if;
  if registered then
    raise exception 'HISTORICAL_SQL_DISABLED: use versioned migrations, not old standalone files';
  end if;
end;
$historical_guard$;
do $pre_cny_guard$
begin
  if to_regprocedure('public.cny_funding_ready()') is not null then
    raise exception 'HISTORICAL_SQL_DISABLED: this file must not overwrite current CNY funding functions';
  end if;
end;
$pre_cny_guard$;

-- Run after security-hardening.sql. Existing financial history is unchanged.
alter table public.bookings add column if not exists retail_price jsonb;
alter table public.wallet_transactions add column if not exists amount_mnt numeric(18,0);
alter table public.wallet_transactions add column if not exists fx_rate_mnt numeric(18,6);

create table if not exists public.retail_pricing (
  booking_id uuid not null references public.bookings(id),
  action text not null check(action in ('issue','change','refund')),
  reference text not null,
  snapshot jsonb not null,
  state text not null default 'prepared' check(state in ('prepared','settled','awaiting_settlement')),
  actor_id uuid not null references public.profiles(id),
  settlement_reference text,
  settled_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  primary key(booking_id, action, reference)
);
alter table public.retail_pricing enable row level security;
revoke all on public.retail_pricing from public, anon, authenticated;
grant all on public.retail_pricing to service_role;
-- Bookings contain supplier fare/quote metadata. Agency access goes through
-- the authenticated backend serializer, not a direct raw PostgREST SELECT.
revoke select on public.bookings from anon, authenticated;

create or replace function public.store_retail_price(p_pnr text, p_action text, p_reference text, p_actor uuid, p_snapshot jsonb, p_public jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare b public.bookings; rate numeric; mnt numeric; wallet numeric; supplier numeric;
begin
  select * into b from public.bookings where pnr = p_pnr for update;
  if not found then raise exception 'Booking not found'; end if;
  if not exists(select 1 from public.agencies where id=b.agency_id and active) then raise exception 'Agency is inactive'; end if;
  if not exists(select 1 from public.profiles p where p.id = p_actor and p.active
    and (p.role = 'platform_admin' or (p.agency_id = b.agency_id and
      (p.role = 'office_manager' or b.created_by = p.id)))) then raise exception 'Booking access denied'; end if;
  if p_action not in ('issue','change','refund') or p_reference is null or length(p_reference) not between 1 and 500
    or (p_action = 'issue' and b.status <> 'Reserved') or (p_action <> 'issue' and b.status <> 'Ticketed') then raise exception 'Invalid pricing operation'; end if;
  rate := (p_snapshot->>'rateMnt')::numeric;
  mnt := (p_snapshot->>'amountMnt')::numeric;
  wallet := (p_snapshot->>'walletCny')::numeric;
  supplier := (p_snapshot->>'supplierCny')::numeric;
  if p_snapshot->>'version' is distinct from '1' or rate is null or rate <= 0 or rate > 1000000
    or mnt is null or mnt < 0 or mnt > 100000000000000 or mod(mnt,100) <> 0
    or supplier is null or supplier < 0 or supplier > 10000000000
    or wallet is distinct from round(mnt/rate,2)
    or p_snapshot->>'direction' is distinct from (case when p_action='refund' then 'refund' else 'charge' end)
    or p_public is distinct from (p_snapshot - array['supplierCny','marginCny','adjustmentMnt','conversionResidualMnt']) then
    raise exception 'Invalid retail settlement quote';
  end if;
  if exists(select 1 from public.financial_operations where booking_id=b.id and state in ('pending','needs_review')) then raise exception 'Resolve the current financial operation first'; end if;
  if exists(select 1 from public.retail_pricing where booking_id=b.id and action=p_action and reference=p_reference and state<>'prepared') then raise exception 'Pricing is already settled'; end if;
  insert into public.retail_pricing(booking_id,action,reference,snapshot,actor_id)
    values(b.id,p_action,p_reference,p_snapshot,p_actor)
    on conflict(booking_id,action,reference) do update set snapshot=excluded.snapshot,actor_id=excluded.actor_id,updated_at=now();
  if p_action='issue' then update public.bookings set retail_price=p_public,total_cny=supplier where id=b.id; end if;
end $$;

-- Preserve the audited authorization/idempotency routines and compose the
-- rounded debit inside the SAME database transaction, never a second charge.
do $$ begin
  if to_regprocedure('public.begin_financial_operation_base(uuid,text,text,text,numeric)') is null then
    alter function public.begin_financial_operation(uuid,text,text,text,numeric) rename to begin_financial_operation_base;
  end if;
  if to_regprocedure('public.issue_booking_from_wallet_base(uuid,uuid)') is null then
    alter function public.issue_booking_from_wallet(uuid,uuid) rename to issue_booking_from_wallet_base;
  end if;
  if to_regprocedure('public.record_change_payment_base(text,text,numeric,uuid,boolean)') is null then
    alter function public.record_change_payment(text,text,numeric,uuid,boolean) rename to record_change_payment_base;
  end if;
end $$;

create or replace function public.begin_financial_operation(p_actor uuid,p_pnr text,p_action text,p_reference text,p_amount numeric,p_expected_retail jsonb default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare operation uuid; q public.retail_pricing; b public.bookings; available numeric;
begin
  operation := public.begin_financial_operation_base(p_actor,p_pnr,p_action,p_reference,p_amount);
  select * into b from public.bookings where pnr=p_pnr;
  select * into q from public.retail_pricing where booking_id=b.id and action=p_action and reference=p_reference for update;
  if found then
    if p_expected_retail is distinct from (q.snapshot - array['supplierCny','marginCny','adjustmentMnt','conversionResidualMnt']) then raise exception 'The confirmed retail price changed'; end if;
    if q.state <> 'prepared' or q.updated_at < now()-interval '15 minutes'
      or (p_action<>'refund' and (q.snapshot->>'supplierCny')::numeric <> round(p_amount,2)) then raise exception 'Retail price expired or changed; review the price again'; end if;
    select balance_cny into available from public.wallets where agency_id=b.agency_id for update;
    if p_action<>'refund' and available < (q.snapshot->>'walletCny')::numeric then raise exception 'Insufficient wallet balance'; end if;
    update public.financial_operations set amount_cny=(q.snapshot->>'walletCny')::numeric where id=operation;
  elsif p_expected_retail is not null or (b.retail_price is not null and p_action='issue') then
    raise exception 'Retail price is missing. No supplier payment was sent';
  end if;
  return operation;
end $$;

create or replace function public.apply_retail_debit(p_booking_id uuid,p_action text,p_reference text,p_actor uuid,p_reason text)
returns void language plpgsql security definer set search_path=public as $$
declare b public.bookings; q public.retail_pricing; extra numeric;
begin
  select * into b from public.bookings where id=p_booking_id for update;
  select * into q from public.retail_pricing where booking_id=b.id and action=p_action and reference=p_reference for update;
  if not found or q.state='settled' then return; end if;
  if q.state <> 'prepared' then raise exception 'Invalid settlement state'; end if;
  if not exists(select 1 from public.financial_operations where booking_id=b.id and action=p_action and reference=p_reference and actor_id=p_actor and state='pending') then raise exception 'Verified payment operation required'; end if;
  extra := (q.snapshot->>'walletCny')::numeric - (q.snapshot->>'supplierCny')::numeric;
  if extra<0 then raise exception 'Invalid retail debit'; end if;
  update public.wallets set balance_cny=balance_cny-extra,updated_at=now() where agency_id=b.agency_id;
  update public.wallet_transactions set amount_cny=-(q.snapshot->>'walletCny')::numeric,
    amount_mnt=-(q.snapshot->>'amountMnt')::numeric,fx_rate_mnt=(q.snapshot->>'rateMnt')::numeric
    where agency_id=b.agency_id and reason=p_reason and entry_type='debit';
  if not found then raise exception 'Original payment ledger entry missing'; end if;
  update public.retail_pricing set state='settled',updated_at=now() where booking_id=b.id and action=p_action and reference=p_reference;
end $$;

create or replace function public.issue_booking_from_wallet(p_booking_id uuid,p_actor_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare result jsonb; b public.bookings; q public.retail_pricing;
begin
  result := public.issue_booking_from_wallet_base(p_booking_id,p_actor_id);
  select * into b from public.bookings where id=p_booking_id;
  perform public.apply_retail_debit(b.id,'issue',b.pnr,p_actor_id,'Ticket issue: '||b.pnr);
  select * into q from public.retail_pricing where booking_id=b.id and action='issue' and reference=b.pnr;
  if found then result := result || jsonb_build_object('debitedCny',(q.snapshot->>'walletCny')::numeric,'balanceCny',(select balance_cny from public.wallets where agency_id=b.agency_id)); end if;
  return result;
end $$;

create or replace function public.record_change_payment(p_pnr text,p_app_id text,p_amount numeric,p_actor uuid,p_check_only boolean default false)
returns jsonb language plpgsql security definer set search_path=public as $$
declare b public.bookings; q public.retail_pricing; result jsonb;
begin
  select * into b from public.bookings where pnr=p_pnr;
  if not exists(select 1 from public.profiles p where p.id=p_actor and p.active
    and (p.role='platform_admin' or (p.agency_id=b.agency_id and (p.role='office_manager' or b.created_by=p.id)))) then raise exception 'Booking access denied'; end if;
  select * into q from public.retail_pricing where booking_id=b.id and action='change' and reference=p_app_id;
  if found and q.state='settled' then
    if (q.snapshot->>'supplierCny')::numeric <> round(p_amount,2) then raise exception 'Change amount mismatch'; end if;
    return jsonb_build_object('recorded',true);
  end if;
  result := public.record_change_payment_base(p_pnr,p_app_id,p_amount,p_actor,p_check_only);
  if not p_check_only then perform public.apply_retail_debit(b.id,'change',p_app_id,p_actor,'Change fee payment: '||p_pnr||' | Spring application '||p_app_id); end if;
  return result;
end $$;

-- A successful refund request is NOT a completed supplier settlement.
create or replace function public.retail_operation_completed()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.state='completed' and old.state='pending' then
    update public.retail_pricing set state=case when new.action='refund' then 'awaiting_settlement' else 'settled' end,updated_at=now()
      where booking_id=new.booking_id and action=new.action and reference=new.reference and state='prepared'
      and (new.action='refund' or (new.action='change' and (snapshot->>'walletCny')::numeric=0));
  end if;
  return new;
end $$;
drop trigger if exists retail_operation_completed on public.financial_operations;
create trigger retail_operation_completed after update of state on public.financial_operations
  for each row execute function public.retail_operation_completed();

-- Finance must verify receipt from Spring before explicitly calling this RPC.
-- Matching the supplier amount and a unique booking/reference prevents duplicate credits.
create or replace function public.settle_retail_refund(p_booking_id uuid,p_reference text,p_actor uuid,p_supplier_received numeric,p_settlement_reference text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare b public.bookings; q public.retail_pricing;
begin
  if not exists(select 1 from public.profiles where id=p_actor and active and role='platform_admin') then raise exception 'Administrator access required'; end if;
  if p_settlement_reference is null or length(trim(p_settlement_reference)) not between 5 and 200 then raise exception 'Verified supplier settlement reference required'; end if;
  select * into b from public.bookings where id=p_booking_id for update;
  if not found then raise exception 'Booking not found'; end if;
  select * into q from public.retail_pricing where booking_id=b.id and action='refund' and reference=p_reference for update;
  if not found or p_supplier_received is distinct from (q.snapshot->>'supplierCny')::numeric then raise exception 'Supplier refund amount differs; reconcile before crediting'; end if;
  if q.state='settled' then return jsonb_build_object('alreadySettled',true); end if;
  if q.state<>'awaiting_settlement' or not exists(select 1 from public.financial_operations where booking_id=b.id and action='refund' and reference=p_reference and state='completed') then raise exception 'Refund request has not completed'; end if;
  perform 1 from public.wallets where agency_id=b.agency_id for update;
  if not found then raise exception 'Wallet not found'; end if;
  update public.wallets set balance_cny=balance_cny+(q.snapshot->>'walletCny')::numeric,updated_at=now() where agency_id=b.agency_id;
  if (q.snapshot->>'walletCny')::numeric > 0 then
  insert into public.wallet_transactions(agency_id,entry_type,amount_cny,amount_mnt,fx_rate_mnt,reason,created_by)
    values(b.agency_id,'credit',(q.snapshot->>'walletCny')::numeric,(q.snapshot->>'amountMnt')::numeric,(q.snapshot->>'rateMnt')::numeric,'Refund settled: '||b.pnr||' | '||p_reference,p_actor);
  end if;
  update public.retail_pricing set state='settled',settlement_reference=trim(p_settlement_reference),settled_by=p_actor,updated_at=now()
    where booking_id=b.id and action='refund' and reference=p_reference;
  update public.bookings set itinerary=jsonb_set(itinerary,'{refundHistory}',
    (select coalesce(jsonb_agg(case when entry->'quote'->>'settlementKey'=p_reference then entry || jsonb_build_object('status','settled','settledAt',now()) else entry end),'[]'::jsonb)
      from jsonb_array_elements(coalesce(itinerary->'refundHistory','[]'::jsonb)) entry)) where id=b.id;
  return jsonb_build_object('creditedCny',(q.snapshot->>'walletCny')::numeric,'amountMnt',(q.snapshot->>'amountMnt')::numeric);
end $$;

revoke all on function public.retail_operation_completed() from public,anon,authenticated;
revoke all on function public.settle_retail_refund(uuid,text,uuid,numeric,text) from public,anon,authenticated;
grant execute on function public.settle_retail_refund(uuid,text,uuid,numeric,text) to service_role;

revoke all on function public.store_retail_price(text,text,text,uuid,jsonb,jsonb) from public,anon,authenticated;
revoke all on function public.apply_retail_debit(uuid,text,text,uuid,text) from public,anon,authenticated;
revoke all on function public.begin_financial_operation(uuid,text,text,text,numeric,jsonb) from public,anon,authenticated;
revoke all on function public.issue_booking_from_wallet(uuid,uuid) from public,anon,authenticated;
revoke all on function public.record_change_payment(text,text,numeric,uuid,boolean) from public,anon,authenticated;
grant execute on function public.store_retail_price(text,text,text,uuid,jsonb,jsonb) to service_role;
grant execute on function public.apply_retail_debit(uuid,text,text,uuid,text) to service_role;
grant execute on function public.begin_financial_operation(uuid,text,text,text,numeric,jsonb) to service_role;
grant execute on function public.issue_booking_from_wallet(uuid,uuid) to service_role;
grant execute on function public.record_change_payment(text,text,numeric,uuid,boolean) to service_role;
create or replace function public.retail_pricing_ready() returns boolean language sql security definer set search_path=public as $$
  select to_regprocedure('public.begin_financial_operation(uuid,text,text,text,numeric,jsonb)') is not null
    and to_regprocedure('public.settle_retail_refund(uuid,text,uuid,numeric,text)') is not null;
$$;
revoke all on function public.retail_pricing_ready() from public,anon,authenticated;
grant execute on function public.retail_pricing_ready() to service_role;
notify pgrst, 'reload schema';

commit;
